import '../apis/utils/env.mjs';

// Send the daily Telegram rich message. The markdown is generated by the Worker
// (GET /api/digest) from exactly the same candidate set + ranking the site uses,
// so the brief can never disagree with the homepage ordering.
//   node scripts/telegram-brief.mjs                 # send today's brief
//   node scripts/telegram-brief.mjs --dry           # print markdown, do not send
//   node scripts/telegram-brief.mjs --lang=ja
//   node scripts/telegram-brief.mjs --boards=ai,crypto

const args = process.argv.slice(2);
const dry = args.includes('--dry');
const langArg = (args.find(a => a.startsWith('--lang=')) || '').split('=')[1];
const lang = ['ja', 'en', 'zh'].includes(langArg) ? langArg : (process.env.BRIEF_LANG || 'zh');
const boardsArg = (args.find(a => a.startsWith('--boards=')) || '').split('=')[1] || '';
const base = process.env.RADAR_URL || 'https://radar.antist.ai';
const token = process.env.RADAR_INGEST_TOKEN;
const HDR = { 'User-Agent': 'antist-radar-brief/1.0', ...(token ? { Authorization: `Bearer ${token}` } : {}) };

const qs = new URLSearchParams({ lang });
if (boardsArg) qs.set('boards', boardsArg);
const r = await fetch(`${base}/api/digest?${qs}`, { headers: HDR, signal: AbortSignal.timeout(40000) });
const j = await r.json().catch(() => ({}));
if (!r.ok || !j.ok || !j.markdown) throw new Error(`digest endpoint failed (${r.status}) ${j.error || ''}`);
if (dry) { console.log(j.markdown); process.exit(0); }

const chat = process.env.TELEGRAM_CHAT_ID;
if (!process.env.TELEGRAM_BOT_TOKEN || !chat) throw new Error('Missing TELEGRAM_BOT_TOKEN / TELEGRAM_CHAT_ID');
const body = { chat_id: chat, rich_message: { markdown: j.markdown } };
if (process.env.TELEGRAM_THREAD_ID) body.message_thread_id = Number(process.env.TELEGRAM_THREAD_ID);

const send = await fetch(`https://api.telegram.org/bot${process.env.TELEGRAM_BOT_TOKEN}/sendRichMessage`, {
  method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body), signal: AbortSignal.timeout(20000),
});
const d = await send.json();
console.log(JSON.stringify({ ok: d.ok, status: send.status, messageId: d.result?.message_id, events: j.events, error: d.description }));
if (!send.ok || !d.ok) process.exit(1);
