import {Hono} from 'hono';
import {html} from 'hono/html';
import {publicSnapshot,resolveForecast} from '../../engine/lib/radar-contract.mjs';
import {ORIGIN,languages,titles,descriptions,type Locale} from './seo';
import {sendDigest,buildMarkdown} from './delivery';
import {getMarkets,setWatchlist,searchSymbols} from './markets';
type Bindings=Env & {RADAR_INGEST_TOKEN:string;TELEGRAM_BOT_TOKEN?:string;TELEGRAM_CHAT_ID?:string;GH_DISPATCH_TOKEN?:string;TG_WEBHOOK_SECRET?:string};
type Snapshot=ReturnType<typeof publicSnapshot>;
const app=new Hono<{Bindings:Bindings}>();
const KEY='radar:public';
const BOARDS=['ai','tech','japan-residence','japan-life','geopolitics','crypto','stocks'] as const;
const STRIP=['BTC-USD','ETH-USD','SOL-USD','^GSPC','^IXIC','^N225','NVDA','^VIX'];
const words={
  en:{tag:'Independent intelligence',hero:'Know what changed.',sub:'Decide what matters.',intro:'A considered view of Japan and the world. Evidence first, useful signals, and predictions that stay on the record.',brief:'The briefing',signals:'Signals',markets:'Markets',editLayout:'Edit layout',addSymbol:'Add symbol…',done:'Done',hint:'Search a symbol to add · drag to reorder · hide or remove in edit mode',all:'All',ai:'AI',tech:'Tech',"japan-residence":'Residency & rules',"japan-life":'Japan · everyday life',geopolitics:'Geopolitics',crypto:'Crypto',stocks:'Stocks',ledger:'Prediction ledger',sources:'Source health',stale:'Data is stale. Check the original before acting.',empty:'The first verified briefing is being prepared.',search:'Search signals…',audience:'Who it affects',action:'Editor\u2019s take',unknowns:'What remains unknown',evidence:'Read the evidence',original:'Original source',disclaimer:'Experimental forecast, not investment advice. The first fresh observation after the deadline determines the result.',due:'Resolves after',prob:'Probability',open:'Open',hit:'Hit',miss:'Miss',unresolved:'Unresolved',noForecast:'No forecast has been published yet.',noresults:'No matching signals.',method:'Method',methodText:'Public sources are checked, changes are deduplicated, and native editions are written from the same evidence. Selection is editorial and bounded, not an exhaustive feed. Unknown applicability stays unknown. No personal profiles are published.',healthy:'healthy sources',before:'Published forecasts are immutable. Misses remain visible.',read:'Read the source',listen:'Listen',generated:'AI-assisted analysis · primary-source verification required',overview:'Overview',more:'View all',archive:'All news',back:'Back',older:'Older',newer:'Newer',bhint:'Drag to reorder · hide or show topics',editBoards:'Edit topics',subscribe:'Subscribe to the Telegram brief',subintro:'Get one rich daily brief via your own Telegram bot — the day\u2019s news across 7 topics plus forecasts and today\u2019s smallest actions.',subtoken:'Bot token',sublang:'Language',subtime:'Time (JST)',subboards:'Topics (none = all)',subgo:'Register',subcmd:'Commands: /brief now · /topics ai,crypto · /time 8 · /stop · /help',subopen:'Open @Antist_monitor_bot',subprivacy:'Privacy: we never collect your bot token. Settings live only in your own Telegram session; others cannot view or change them. Send /delete to erase everything.',deadline:'due',page:'Page'},
  ja:{tag:'独立インテリジェンス',hero:'変化を捉える。',sub:'判断につなげる。',intro:'日本と世界を根拠から読み解く。役立つ変化と、結果を検証できる予測を。',brief:'今回の見立て',signals:'注目の変化',markets:'マーケット',editLayout:'表示を編集',addSymbol:'銘柄を追加…',done:'完了',hint:'銘柄を検索して追加 · ドラッグで並べ替え · 編集モードで非表示/削除',all:'すべて',ai:'AI',tech:'テック',"japan-residence":'在留・制度',"japan-life":'日本での暮らし',geopolitics:'地政学',crypto:'暗号資産',stocks:'株式',ledger:'予測の記録',sources:'情報源の状態',stale:'情報が古くなっています。行動の前に原文を確認してください。',empty:'検証済みの初回ブリーフィングを準備中です。',search:'変化を検索…',audience:'関係する人',action:'本サイトの見解',unknowns:'未確認の点',evidence:'根拠を確認',original:'一次情報',disclaimer:'実験的な予測であり、投資助言ではありません。期限後の最初の新しい観測で判定します。',due:'判定開始',prob:'確率',open:'未決着',hit:'的中',miss:'不的中',unresolved:'判定保留',noForecast:'公開された予測はまだありません。',noresults:'該当する情報はありません。',method:'編集方針',methodText:'公開情報を確認し、変化を重複なく追跡。同じ根拠から各言語で独立した文章を作成します。全件収集ではなく、範囲を定めた編集です。適用条件が不明なら不明と示し、個人の情報は公開しません。',healthy:'正常な情報源',before:'公開した予測は書き換えません。外れた記録も残します。',read:'原文を読む',listen:'読み上げ',generated:'AI 支援による分析 · 一次情報で要確認',overview:'概要',more:'もっと見る',archive:'過去の記事',back:'戻る',older:'古い',newer:'新しい',bhint:'ドラッグで並べ替え · 表示/非表示',editBoards:'表示を編集',subscribe:'Telegram で毎日購読',subintro:'自分の Telegram bot で、その日のニュースを1通のリッチなブリーフにまとめて受け取る（7テーマ＋予測＋今日の最小アクション）。',subtoken:'Bot token',sublang:'言語',subtime:'配信時刻（JST）',subboards:'テーマ（未選択＝すべて）',subgo:'登録',subcmd:'コマンド：/brief · /topics ai,crypto · /time 8 · /stop · /help',subopen:'@Antist_monitor_bot を開く',subprivacy:'プライバシー：bot token は受け取りません。設定はあなたの Telegram セッション内でのみ有効で、他人は閲覧・変更できません。/delete で完全に削除できます。',deadline:'締切',page:'ページ'},
  zh:{tag:'独立情报',hero:'看见变化。',sub:'形成判断。',intro:'从依据出发观察日本与世界。先看证据，只看有用的变化，每次预判都留下可核查的记录。',brief:'本期判断',signals:'信号',markets:'行情',editLayout:'编辑布局',addSymbol:'添加代码…',done:'完成',hint:'搜索代码添加 · 拖拽排序 · 编辑模式可隐藏或删除',all:'全部',ai:'AI 圈',tech:'科技',"japan-residence":'日本在留',"japan-life":'日本生活',geopolitics:'地缘政治',crypto:'加密',stocks:'股票',ledger:'预测记账本',sources:'信源状态',stale:'数据已陈旧，采取行动前请核对原文。',empty:'正在准备首份经过核验的简报。',search:'搜索信号…',audience:'影响谁',action:'本站评价',unknowns:'尚未确认',evidence:'查看依据',original:'原始来源',disclaimer:'实验性预测，不构成投资建议。以到期后首次新报价判定结果。',due:'开始结算',prob:'概率',open:'待结算',hit:'命中',miss:'未命中',unresolved:'待核查',noForecast:'尚无已发布预测。',noresults:'没有匹配的信号。',method:'编辑方法',methodText:'核查公开信源、识别变化并去重，从同一组依据分别写成三语内容。这里是有范围的编辑筛选，不是全量信息流。资格不明就保留未知，不公开任何个人匹配资料。',healthy:'健康信源',before:'预测发布后保留原文，未命中的记录也不会删除。',read:'阅读原文',listen:'朗读',generated:'AI 辅助分析 · 行动前请核对一手来源',overview:'概览',more:'查看更多',archive:'全部新闻',back:'返回',older:'更早',newer:'更新',bhint:'拖拽排序 · 显示或隐藏主题',editBoards:'编辑主题',subscribe:'订阅 Telegram 每日简报',subintro:'用你自己的 Telegram bot 接收，每天一条，汇总当日全部新闻（7 大主题 + 预测 + 今日最小动作）。',subtoken:'Bot token',sublang:'语言',subtime:'推送时间（JST）',subboards:'主题（不选 = 全部）',subgo:'注册',subcmd:'命令：/brief 立即发一份 · /topics ai,crypto · /time 8 · /stop · /help',subopen:'打开 @Antist_monitor_bot',subprivacy:'隐私：不收集你的 bot token；设置只存在于你自己的 Telegram 会话里，别人无法查看或更改；发送 /delete 可彻底删除全部数据。',deadline:'截止',page:'页'}
};
function formatDate(s:string,l:Locale){return new Intl.DateTimeFormat(l==='zh'?'zh-CN':l==='ja'?'ja-JP':'en-GB',{timeZone:'Asia/Tokyo',month:'short',day:'numeric',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(s))+' JST';}
function EventCard({e,index,l,w}:{e:any;index:number;l:Locale;w:Record<string,string>}){
  return <article data-event data-category={e.category} class="card card-hover p-5 animate-in">
    <div class="flex items-center justify-between mb-3"><span class="badge badge-secondary">{w[e.category]||e.category}</span><span class="text-[11px] text-muted-foreground truncate ml-3">{e.source}</span></div>
    <a href={e.url} target="_blank" rel="noopener noreferrer"><h3 data-tts-title class="font-semibold leading-snug">{e.title[l]} <span class="text-muted-foreground">↗</span></h3></a>
    {(e.publishedAt||e.deadlineAt)&&<p class="text-[11px] text-muted-foreground mt-1.5">{e.publishedAt?formatDate(e.publishedAt,l):''}{e.publishedAt&&e.deadlineAt?' · ':''}{e.deadlineAt?((w.deadline||'due')+' '+formatDate(e.deadlineAt,l)):''}</p>}
    <p data-tts-summary class="text-sm text-muted-foreground mt-2 leading-relaxed">{e.summary[l]}</p>
    <div class="mt-4 rounded-lg border bg-muted/40 p-4"><p class="text-[10px] font-semibold uppercase tracking-wide text-muted-foreground mb-1">{w.action}</p><p data-tts-review class="text-sm leading-relaxed">{e.action[l]}</p></div>
    <details class="mt-4 text-xs text-muted-foreground"><summary class="cursor-pointer select-none">{w.evidence}</summary><dl class="mt-3 space-y-2 leading-relaxed"><div><dt class="font-semibold text-foreground/80">{w.audience}</dt><dd>{e.audience[l]}</dd></div><div><dt class="font-semibold text-foreground/80">{w.unknowns}</dt><dd>{e.unknowns[l]}</dd></div><div><dt class="font-semibold text-foreground/80">{w.original}</dt><dd>{e.evidence}</dd></div></dl><a href={e.url} target="_blank" rel="noopener noreferrer" class="inline-block mt-3 underline">{w.read}</a></details>
  </article>;
}
function ForecastCard({r,l,w}:{r:any;l:Locale;w:Record<string,string>}){const claim=JSON.parse(String(r.claim_json));const rationale=JSON.parse(String(r.rationale_json));return <div class="card p-5"><div class="flex items-center justify-between mb-4"><span class="badge badge-secondary">{w[String(r.status) as keyof typeof w]||r.status}</span><span class="text-xs text-muted-foreground tabular-nums">{String(r.created_at).slice(0,10)}</span></div><h3 data-tts-title class="font-semibold leading-relaxed">{claim[l]}</h3><p data-tts-summary class="text-sm text-muted-foreground mt-2 leading-relaxed">{rationale[l]}</p><div class="grid grid-cols-2 gap-4 border-t mt-5 pt-4"><div><div class="text-[10px] text-muted-foreground">{w.prob}</div><div class="text-2xl font-semibold tabular-nums mt-0.5">{Math.round(Number(r.probability)*100)}%</div></div><div><div class="text-[10px] text-muted-foreground">{w.due}</div><div class="text-xs tabular-nums mt-1.5">{formatDate(String(r.due_at),l)}</div></div></div>{r.observed!=null&&<p class="text-xs tabular-nums mt-3">{r.symbol}: {r.observed} · {r.observation_at}</p>}<p class="text-[10px] text-muted-foreground mt-4 leading-relaxed">{w.disclaimer}</p></div>;}
async function ledger(db:D1Database){return (await db.prepare('SELECT * FROM forecasts ORDER BY created_at DESC LIMIT 10').all()).results;}
async function settle(env:Bindings,s:Snapshot){
  const rows=(await env.DB.prepare("SELECT * FROM forecasts WHERE status='open' AND due_at<=? LIMIT 100").bind(new Date().toISOString()).all()).results;
  for(const r of rows){const result=resolveForecast({symbol:r.symbol,baseline:r.baseline,direction:r.direction,dueAt:r.due_at},s.markets);
    if(result)await env.DB.prepare("UPDATE forecasts SET status=?,observed=?,observation_at=?,resolved_at=? WHERE id=? AND status='open'").bind(result.status,result.observed,result.observationAt,result.resolvedAt,r.id).run();}
}
// Keep only the last 10 days on the site; older events move to events_archive (kept as backup).
const RETAIN_DAYS=10;
async function retain(env:Bindings){
  const cutoff=new Date(Date.now()-RETAIN_DAYS*86400000).toISOString();
  const cols='id,source,category,url,published_at,first_seen,last_seen,stage,deadline_at,change,title_json,summary_json,audience_json,action_json,unknowns_json,evidence,score';
  const cond="COALESCE(NULLIF(published_at,''),first_seen)<?";
  const a=await env.DB.prepare(`INSERT OR REPLACE INTO events_archive (${cols},archived_at) SELECT ${cols},? FROM events WHERE ${cond}`).bind(new Date().toISOString(),cutoff).run();
  const d=await env.DB.prepare(`DELETE FROM events WHERE ${cond}`).bind(cutoff).run();
  return {archived:a.meta.changes,deleted:d.meta.changes,cutoff};
}
// GitHub's scheduled workflows are unreliable on new repos, so the Worker's own
// cron (reliable) dispatches the sweep when the snapshot goes stale.
async function dispatchSweep(env:Bindings){if(!env.GH_DISPATCH_TOKEN)return {ok:false,reason:'GH_DISPATCH_TOKEN unset'};try{const r=await fetch('https://api.github.com/repos/Antisubmissivist/antist-radar/actions/workflows/sweep.yml/dispatches',{method:'POST',headers:{Authorization:`Bearer ${env.GH_DISPATCH_TOKEN}`,Accept:'application/vnd.github+json','User-Agent':'antist-radar','Content-Type':'application/json'},body:JSON.stringify({ref:'main'})});return {ok:r.ok,status:r.status};}catch(e){return {ok:false,reason:String(e)};}}
function briefingText(s:Snapshot,l:Locale){const ev=s.events.slice(0,8);const lines=[`Antist Radar · ${formatDate(s.generatedAt,l)}`,'',s.digest[l],''];for(const e of ev){lines.push(`• ${e.title[l]}`,`  ${e.action[l]}`,`  ${e.url}`);}for(const f of (s.forecasts||[])){lines.push('',`Forecast: ${f.symbol} ${f.direction} ${Math.round(Number(f.probability)*100)}% (due ${f.dueAt.slice(0,10)})`);}return lines.join('\n');}
function rowToEvent(r:Record<string,unknown>):any{const j=(v:unknown)=>{try{return JSON.parse(String(v));}catch{return null;}};return {id:String(r.id),source:String(r.source),category:String(r.category),url:String(r.url),publishedAt:r.published_at?String(r.published_at):null,fetchedAt:String(r.first_seen),stage:String(r.stage||'announcement'),deadlineAt:r.deadline_at?String(r.deadline_at):null,title:j(r.title_json),summary:j(r.summary_json),audience:j(r.audience_json),action:j(r.action_json),unknowns:j(r.unknowns_json),evidence:String(r.evidence||''),change:String(r.change||'unchanged'),score:Number(r.score||0)};}
// ---- Telegram self-serve subscribers ----
async function tgApi(token:string,method:string,body:unknown){try{const r=await fetch(`https://api.telegram.org/bot${token}/${method}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body),signal:AbortSignal.timeout(12000)});const j=await r.json() as Record<string,unknown>;if(!j.ok)console.log(JSON.stringify({event:'tg-api-fail',method,detail:j.description}));return j;}catch(e){console.log(JSON.stringify({event:'tg-api-error',method,error:String(e)}));return {ok:false,error:String(e)};}}
function newSecret(){return crypto.randomUUID().replace(/-/g,'');}
function normBoards(v:unknown){if(!Array.isArray(v))return [];return v.map(String).filter(b=>(BOARDS as readonly string[]).includes(b));}
async function latestSnapshot(env:Bindings){try{const list=await env.ARCHIVE.list({prefix:'snapshots/',limit:1000});const objs=((list.objects||[]) as {key:string;uploaded:string|Date}[]).slice().sort((a,b)=>new Date(b.uploaded).getTime()-new Date(a.uploaded).getTime());if(objs[0]){const o=await env.ARCHIVE.get(objs[0].key);if(o)return await o.json() as Snapshot;}}catch{}return env.MONITOR.get<Snapshot>(KEY,'json');}
// On-demand brief: rolling last 24h. Calendar-day windows are empty right after
// JST midnight (the day's news has not accumulated yet), which made /brief show 0.
async function briefPayload(env:Bindings){const end=Date.now();const start=end-24*3600000;const s0=new Date(start).toISOString();const e0=new Date(end).toISOString();const ev=await env.DB.prepare('SELECT * FROM events WHERE first_seen>=? AND first_seen<? ORDER BY COALESCE(published_at,first_seen) DESC LIMIT 400').bind(s0,e0).all();const fcr=await env.DB.prepare('SELECT * FROM forecasts WHERE created_at>=? AND created_at<? ORDER BY created_at DESC LIMIT 20').bind(s0,e0).all();const s=await latestSnapshot(env);const forecasts=(fcr.results||[]).map(r=>({id:String(r.id),symbol:String(r.symbol),direction:r.direction==='above'?'above':'below',probability:Number(r.probability),dueAt:String(r.due_at),claim:JSON.parse(String(r.claim_json))}));return {generatedAt:new Date(end).toISOString(),digest:s?s.digest:null,events:(ev.results||[]).map(rowToEvent),forecasts,count:(ev.results||[]).length};}
async function dailyPayload(env:Bindings,date:string){const start=new Date(Date.parse(date+'T00:00:00+09:00')).toISOString();const end=new Date(Date.parse(date+'T00:00:00+09:00')+86400000).toISOString();const ev=await env.DB.prepare('SELECT * FROM events WHERE first_seen>=? AND first_seen<? ORDER BY COALESCE(published_at,first_seen) DESC LIMIT 400').bind(start,end).all();const fcr=await env.DB.prepare('SELECT * FROM forecasts WHERE created_at>=? AND created_at<? ORDER BY created_at DESC LIMIT 20').bind(start,end).all();let digest:unknown=null;try{const list=await env.ARCHIVE.list({prefix:'snapshots/'+date+'/',limit:200});const keys=((list.objects||[]) as {key:string}[]).map(o=>o.key).sort();const last=keys[keys.length-1];if(last){const obj=await env.ARCHIVE.get(last);if(obj){const j=await obj.json() as {digest?:unknown};digest=(j&&j.digest)?j.digest:null;}}}catch{}const forecasts=(fcr.results||[]).map(r=>({id:String(r.id),symbol:String(r.symbol),direction:r.direction==='above'?'above':'below',probability:Number(r.probability),dueAt:String(r.due_at),claim:JSON.parse(String(r.claim_json))}));return {date,generatedAt:date+'T00:00:00+09:00',digest,events:(ev.results||[]).map(rowToEvent),forecasts,count:(ev.results||[]).length};}
async function sendSubscriber(env:Bindings,sub:Record<string,unknown>,date:string){const boards=normBoards((()=>{try{return JSON.parse(String(sub.boards||'[]'));}catch{return [];}})());const p=await briefPayload(env);const md=buildMarkdown(p,String(sub.lang||'zh'),boards.length?boards:undefined);const token=/^\d{6,}:[A-Za-z0-9_-]{30,}$/.test(String(sub.token||''))?String(sub.token):String(env.TELEGRAM_BOT_TOKEN||'');const extra=sub.thread_id?{message_thread_id:Number(sub.thread_id)}:{};return tgApi(token,'sendRichMessage',{chat_id:String(sub.chat_id),...extra,rich_message:{markdown:md}});}
const TG_COMMANDS=[{command:'brief',description:'立即发送今日简报 · Today\u2019s brief now'},{command:'topics',description:'设置主题，如 /topics ai,crypto'},{command:'time',description:'设置推送小时，如 /time 8'},{command:'lang',description:'切换语言 · Language (zh|ja|en)'},{command:'stop',description:'停止推送 · Stop'},{command:'start',description:'恢复推送 · Resume'},{command:'help',description:'帮助 · Help'}];
function subHelp(sub:Record<string,unknown>,isStart?:boolean){const b=normBoards((()=>{try{return JSON.parse(String(sub.boards||'[]'));}catch{return [];}})());const sched=Number(sub.hour)>=0?('每天 **'+String(sub.hour)+':41 JST** 推送'):'当前为命令模式（不自动推送，用 `/time 8` 开启）';return [(isStart?'**订阅成功 ✅**':'**Antist Radar bot**'),'',sched+'，主题：'+(b.length?b.join(', '):'全部')+'，语言：'+String(sub.lang)+'（`/lang` 切换）','','你的设置只在本聊天里生效，别人无法更改。','**命令**','- `/brief` 立即发一份今日简报','- `/topics ai,crypto` 订阅这些主题','- `/time 8` 推送时间（0-23 JST）','- `/lang zh|ja|en` 切换语言','- `/stop` 暂停 · `/start` 恢复','- `/delete` 彻底删除你的订阅数据','- `/help` 帮助'].join('\n');}
function subTopics(){return '_'+(BOARDS as readonly string[]).join('_, _')+'_';}
const LANGS=['zh','ja','en'];const LANG_OK={zh:'✅ 已切换为中文。',ja:'✅ 日本語に切り替えました。',en:'✅ Language set to English.'};const LANG_USE={zh:'用法：/lang zh | ja | en',ja:'使い方：/lang ja | en | zh',en:'Usage: /lang en | ja | zh'};
function SiteHeader({l,w,cat}:{l:Locale;w:Record<string,string>;cat?:string}){const href=(lang:string)=>cat?`/${lang}/c/${cat}`:`/${lang}`;return <header class="sticky top-0 z-40 w-full border-b bg-background/80 backdrop-blur supports-[backdrop-filter]:bg-background/60"><div class="mx-auto max-w-6xl h-16 px-4 md:px-6 flex items-center justify-between gap-4"><a href={`/${l}`} class="flex items-center gap-2 font-semibold tracking-tight"><span class="logo-icon"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="1.7" fill="currentColor" stroke="none"/><path d="M12 12 19 5"/><path d="M5.5 12a6.5 6.5 0 0 1 6.5-6.5"/><path d="M8.5 12a3.5 3.5 0 0 1 3.5-3.5"/><path d="M2.5 12a9.5 9.5 0 0 1 9.5-9.5" opacity=".5"/></svg></span><span>ANTIST<span class="text-muted-foreground font-normal"> / RADAR</span></span></a><nav class="hidden md:flex items-center gap-1"><a href={`/${l}`} class="navlink">{w.overview}</a><a href={`/${l}#markets`} class="navlink">{w.markets}</a><a href={`/${l}#ledger`} class="navlink">{w.ledger}</a><a href={`/${l}#sources`} class="navlink">{w.sources}</a></nav><div class="flex items-center gap-2"><div class="flex items-center rounded-lg bg-muted p-1">{languages.map(lang=><a href={href(lang)} class={`tab px-2.5 py-1 text-xs ${lang===l?'tab-active':''}`}>{lang.toUpperCase()}</a>)}</div><button data-theme class="btn btn-ghost btn-icon relative" aria-label="Toggle theme"><svg class="h-4 w-4 rotate-0 scale-100 transition-all dark:-rotate-90 dark:scale-0" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="4"/><path d="M12 2v2M12 20v2M4.93 4.93l1.41 1.41M17.66 17.66l1.41 1.41M2 12h2M20 12h2M6.34 17.66l-1.41 1.41M19.07 4.93l-1.41 1.41"/></svg><svg class="absolute inset-0 m-auto h-4 w-4 rotate-90 scale-0 transition-all dark:rotate-0 dark:scale-100" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 3a6 6 0 0 0 9 9 9 9 0 1 1-9-9Z"/></svg></button></div></div></header>;}
function SiteFooter({w}:{w:Record<string,string>}){return <footer class="border-t"><div class="mx-auto max-w-6xl px-4 md:px-6 py-10 grid md:grid-cols-[1.2fr_1fr] gap-8"><div><p class="text-sm font-semibold tracking-tight">ANTIST / RADAR.</p><p class="text-xs text-muted-foreground mt-3">Japan & the world. Independently observed.</p><p class="text-xs text-muted-foreground mt-4">© {new Date().getFullYear()} Antist · All rights reserved.</p><a class="text-xs text-muted-foreground underline mt-2 inline-block" href="https://github.com/Antisubmissivist/antist-radar">Source code · AGPL-3.0</a></div><div><h2 class="text-xs font-semibold mb-2">{w.method}</h2><p class="text-xs text-muted-foreground leading-relaxed">{w.methodText}</p></div></div></footer>;}
function pageHead(l:Locale,path:string){return <head><meta charset="utf-8"/><meta name="viewport" content="width=device-width,initial-scale=1"/><title>{titles[l]}</title><meta name="description" content={descriptions[l]}/><link rel="canonical" href={`${ORIGIN}${path}`}/>{languages.map(lang=><link rel="alternate" hreflang={lang} href={`${ORIGIN}${path.replace(`/${l}`,`/${lang}`)}`}/>)}<link rel="alternate" hreflang="x-default" href={`${ORIGIN}${path.replace(`/${l}`,'/en')}`}/><meta property="og:title" content={titles[l]}/><meta property="og:description" content={descriptions[l]}/><meta property="og:url" content={`${ORIGIN}${path}`}/><meta property="og:type" content="website"/><meta property="og:image" content={`${ORIGIN}/og.png`}/><meta property="og:image:width" content="1200"/><meta property="og:image:height" content="630"/><meta name="twitter:card" content="summary_large_image"/><meta name="twitter:image" content={`${ORIGIN}/og.png`}/><meta name="theme-color" content="#0a0a0b"/><link rel="icon" type="image/png" sizes="512x512" href="/favicon-512.png"/><link rel="icon" type="image/png" sizes="32x32" href="/favicon-32.png"/><link rel="apple-touch-icon" href="/apple-touch-icon.png"/><link rel="stylesheet" href="/style.css"/>{html`<script>try{if((localStorage.getItem('radar-theme')||'dark')==='dark')document.documentElement.classList.add('dark')}catch{}</script>`}<script src="/app.js" defer/></head>;}
app.use('*',async(c,next)=>{await next();if(!c.res.headers.has('Cache-Control'))c.header('Cache-Control','no-store');c.header('X-Content-Type-Options','nosniff');c.header('Referrer-Policy','strict-origin-when-cross-origin');c.header('X-Frame-Options','DENY');});
app.get('/',c=>c.redirect('/en',302));
app.get('/robots.txt',c=>c.text(`User-agent: *\nAllow: /\nDisallow: /api/ingest\nSitemap: ${ORIGIN}/sitemap.xml`));
app.get('/sitemap.xml',c=>c.body(`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${languages.map(l=>`<url><loc>${ORIGIN}/${l}</loc></url>`).join('')}</urlset>`,200,{'Content-Type':'application/xml'}));
app.get('/api/public',async c=>{const s=await latestSnapshot(c.env);c.header('Cache-Control','no-store');return s?c.json(s):c.json({status:'pending'},503);});
app.get('/api/ledger',async c=>c.json({forecasts:await ledger(c.env.DB)}));
app.get('/api/markets',async c=>{const q=c.req.query('symbols');const symbols=q?q.split(',').map(x=>x.trim()).filter(Boolean):undefined;const m=await getMarkets(c.env,symbols);c.header('Cache-Control','no-store');return c.json(m);});
app.get('/api/symbols',async c=>{const q=(c.req.query('q')||'').trim();if(!q)return c.json({results:[]});c.header('Cache-Control','public, max-age=300');return c.json({results:await searchSymbols(q.slice(0,40))});});
app.get('/api/briefing',async c=>{const raw=c.req.query('lang')||'zh';const L=(languages as readonly string[]).includes(raw)?raw as Locale:'zh';const s=await latestSnapshot(c.env);if(!s)return c.json({status:'pending'},503);const events=s.events.slice(0,8).map(e=>({category:e.category,title:e.title[L],action:e.action[L],url:e.url}));const forecasts=(s.forecasts||[]).map(f=>({symbol:f.symbol,direction:f.direction,probability:f.probability,dueAt:f.dueAt,claim:f.claim[L]}));c.header('Cache-Control','no-store');if(c.req.query('format')==='text')return c.text(briefingText(s,L));return c.json({lang:L,updatedAt:s.generatedAt,digest:s.digest[L],events,forecasts,text:briefingText(s,L)});});
app.post('/api/dispatch',async c=>{const expected=`Bearer ${c.env.RADAR_INGEST_TOKEN||''}`;if(!c.env.RADAR_INGEST_TOKEN||c.req.header('Authorization')!==expected)return c.json({ok:false},401);return c.json(await dispatchSweep(c.env));});
app.get('/llms.txt',c=>c.text(['# Antist Radar API','','Independent Japan+world intelligence radar. Public, read-only JSON.','','GET /api/public            Full snapshot (schema 2): digest(ja/en/zh), events, markets, sources, forecasts','GET /api/briefing?lang=zh  Concise briefing for agents/Telegram; add &format=text for plain text','GET /api/ledger            Published forecasts and their settled results','GET /api/markets?symbols=  Live quotes for any comma-separated Yahoo symbols','GET /api/symbols?q=        Symbol search (returns symbol, name, exchange)','','Write endpoints require Authorization: Bearer <token>:','POST /api/ingest  POST /api/digest  POST /api/watchlist  POST /api/dispatch','','Forecasts are experimental and not investment advice.'].join('\n'),200,{'Content-Type':'text/plain; charset=utf-8'}));
app.get('/api/events',async c=>{const cat=c.req.query('category');const limit=Math.min(100,Math.max(1,Number(c.req.query('limit'))||40));const page=Math.max(1,Number(c.req.query('page'))||1);const off=(page-1)*limit;const sql=cat?'SELECT * FROM events WHERE category=? ORDER BY COALESCE(published_at,first_seen) DESC LIMIT ? OFFSET ?':'SELECT * FROM events ORDER BY COALESCE(published_at,first_seen) DESC LIMIT ? OFFSET ?';const st=c.env.DB.prepare(sql);const res=await (cat?st.bind(cat,limit+1,off):st.bind(limit+1,off)).all();const rows=(res.results||[]);c.header('Cache-Control','no-store');return c.json({category:cat||null,page,hasMore:rows.length>limit,events:rows.slice(0,limit).map(rowToEvent)});});
app.post('/api/events/review',async c=>{const expected=`Bearer ${c.env.RADAR_INGEST_TOKEN||''}`;if(!c.env.RADAR_INGEST_TOKEN||c.req.header('Authorization')!==expected)return c.json({ok:false},401);const b=await c.req.json().catch(()=>null) as {updates?:unknown}|null;const ups=Array.isArray(b?.updates)?(b!.updates as Record<string,any>[]):[];const stmts=[];for(const u of ups){const id=String(u?.id||'');const act=u?.action;if(!id||!act||typeof act!=='object')continue;const a=Object.fromEntries(['ja','en','zh'].map(l=>[l,String(act[l]||'').slice(0,600)]));stmts.push(c.env.DB.prepare('UPDATE events SET action_json=? WHERE id=?').bind(JSON.stringify(a),id));}if(stmts.length)await c.env.DB.batch(stmts);return c.json({ok:true,updated:stmts.length});});
app.get('/api/daily',async c=>{const date=(c.req.query('date')||new Date(Date.now()+9*3600000).toISOString().slice(0,10));c.header('Cache-Control','no-store');return c.json(await dailyPayload(c.env,date));});
app.post('/api/subscribe',async c=>{const b=await c.req.json().catch(()=>null) as Record<string,unknown>|null;const token=String(b?.token||'').trim();if(!/^\d{6,}:[A-Za-z0-9_-]{30,}$/.test(token))return c.json({ok:false,reason:'invalid token format'},400);const me=await tgApi(token,'getMe',{});if(!me.ok)return c.json({ok:false,reason:'token rejected by Telegram',detail:me.description||me.error},400);const botUsername=String((me.result as Record<string,unknown>)?.username||'');const secret=newSecret();const ws=newSecret();const pair=secret.slice(0,6).toUpperCase();const lang=(['ja','en','zh'].includes(String(b?.lang))?String(b?.lang):'zh');const auto=(b?.auto!==false);const hour=auto?Math.min(23,Math.max(0,Number(b?.hour)||8)):-1;const boards=normBoards(b?.boards);const id=crypto.randomUUID();await c.env.DB.prepare('INSERT INTO subscribers (id,secret,token,bot_username,lang,hour,boards,active,created_at,webhook_secret,pair_code) VALUES (?,?,?,?,?,?,?,1,?,?,?)').bind(id,secret,token,botUsername,lang,hour,JSON.stringify(boards),new Date().toISOString(),ws,pair).run();const wh=await tgApi(token,'setWebhook',{url:`${ORIGIN}/api/tg/${secret}`,secret_token:ws,allowed_updates:['message'],drop_pending_updates:true});if(!wh.ok){await c.env.DB.prepare('DELETE FROM subscribers WHERE id=?').bind(id).run();return c.json({ok:false,reason:'could not set webhook',detail:wh.description||wh.error},502);}await tgApi(token,'setMyCommands',{commands:TG_COMMANDS});return c.json({ok:true,secret,pairCode:pair,botUsername,statusUrl:`${ORIGIN}/api/subscribe/${secret}`});});
app.get('/api/subscribe/:secret',async c=>{const r=await c.env.DB.prepare('SELECT bot_username,chat_id,lang,hour,boards,active,last_sent FROM subscribers WHERE secret=?').bind(c.req.param('secret')).first() as Record<string,unknown>|null;if(!r)return c.json({ok:false},404);let boards=[];try{boards=JSON.parse(String(r.boards||'[]'));}catch{}return c.json({ok:true,botUsername:r.bot_username,linked:!!r.chat_id,lang:r.lang,hour:r.hour,boards,active:!!r.active});});
app.post('/api/subscribe/:secret',async c=>{const secret=c.req.param('secret');const ex=await c.env.DB.prepare('SELECT * FROM subscribers WHERE secret=?').bind(secret).first() as Record<string,unknown>|null;if(!ex)return c.json({ok:false},404);const b=await c.req.json().catch(()=>null) as Record<string,unknown>|null;const lang=(['ja','en','zh'].includes(String(b?.lang))?String(b?.lang):String(ex.lang||'zh'));const hour=(b?.hour!=null?Math.min(23,Math.max(0,Number(b.hour))):Number(ex.hour||8));let boards;try{boards=JSON.parse(String(ex.boards||'[]'));}catch{boards=[];}if(b?.boards!=null)boards=normBoards(b.boards);await c.env.DB.prepare('UPDATE subscribers SET lang=?,hour=?,boards=? WHERE secret=?').bind(lang,hour,JSON.stringify(boards),secret).run();return c.json({ok:true,lang,hour,boards});});
app.post('/api/subscribe/:secret/delete',async c=>{const secret=c.req.param('secret');const ex=await c.env.DB.prepare('SELECT token FROM subscribers WHERE secret=?').bind(secret).first() as Record<string,unknown>|null;if(ex){await tgApi(String(ex.token),'deleteWebhook',{});await c.env.DB.prepare('DELETE FROM subscribers WHERE secret=?').bind(secret).run();}return c.json({ok:true});});
app.post('/api/tg/:secret',async c=>{try{
const rawSecret=c.req.param('secret');const isPublic=rawSecret==='public';
const u=await c.req.json().catch(()=>null) as Record<string,any>|null;const msg=u?.message||u?.edited_message;if(!msg)return c.json({ok:true});
const chatId=String(msg.chat?.id||'');const chatType=String(msg.chat?.type||'private');const threadId=msg.message_thread_id!=null?String(msg.message_thread_id):'';const chatTitle=String(msg.chat?.title||'');const fromId=String(msg.from?.id||'');const text=String(msg.text||'').trim();const parts=text.split(/\s+/);const cmd=(parts[0]||'').toLowerCase().replace(/@.*$/,'');const arg=parts[1]||'';const uid=Number(u?.update_id||0);
let sub:Record<string,any>|null=null;let token='';
if(isPublic){
if(c.req.header('x-telegram-bot-api-secret-token')!==String(c.env.TG_WEBHOOK_SECRET||''))return c.json({ok:true});
token=String(c.env.TELEGRAM_BOT_TOKEN||'');
const st=await c.env.DB.prepare('SELECT v FROM tg_state WHERE k=?').bind('last_update_id').first() as {v?:string}|null;
if(uid&&Number(st?.v||0)>=uid)return c.json({ok:true});
if(uid)await c.env.DB.prepare('INSERT INTO tg_state (k,v) VALUES (?,?) ON CONFLICT(k) DO UPDATE SET v=excluded.v').bind('last_update_id',String(uid)).run();
if(isPublic&&(chatType==='group'||chatType==='supergroup')){
  // In a group the bot reacts when addressed (@Antist_monitor_bot) or on a known
  // command. It then pins the daily digest to that exact topic (chat_id + thread_id).
  const KNOWN=['/start','/help','/brief','/time','/topics','/lang','/stop','/delete'];
  if(!text.toLowerCase().includes('@antist_monitor_bot')&&!KNOWN.includes(cmd))return c.json({ok:true});
  let g=await c.env.DB.prepare('SELECT * FROM subscribers WHERE chat_id=? AND IFNULL(thread_id,\'\')=?').bind(chatId,threadId).first() as Record<string,any>|null;
  if(!g){const id=crypto.randomUUID();await c.env.DB.prepare('INSERT INTO subscribers (id,secret,token,bot_username,chat_id,thread_id,chat_title,owner_user_id,lang,hour,boards,active,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,1,?)').bind(id,newSecret(),'Antist_monitor_bot','Antist_monitor_bot',chatId,threadId,chatTitle,fromId,'zh',8,'[]',new Date().toISOString()).run();g=await c.env.DB.prepare('SELECT * FROM subscribers WHERE id=?').bind(id).first() as Record<string,any>;}
  const extra=threadId?{message_thread_id:Number(threadId)}:{};
  if(cmd==='/brief'){await sendSubscriber(c.env,{...g,chat_id:chatId,token},new Date(Date.now()+9*3600000).toISOString().slice(0,10));}
  else if(cmd==='/start'||cmd==='/help'){await tgApi(token,'sendRichMessage',{chat_id:chatId,...extra,rich_message:{markdown:subHelp(g,cmd==='/start')}});}
  else if(cmd==='/time'){const h=Number(arg);if(Number.isInteger(h)&&h>=0&&h<=23){await c.env.DB.prepare('UPDATE subscribers SET hour=? WHERE id=?').bind(h,g.id).run();await tgApi(token,'sendMessage',{chat_id:chatId,...extra,text:'\u23f0 每天约 '+h+':41 JST 在此话题推送'});}else await tgApi(token,'sendMessage',{chat_id:chatId,...extra,text:'用法: /time 8'});}
  else if(cmd==='/lang'){const L=String(arg||'').toLowerCase();if(LANGS.includes(L)){await c.env.DB.prepare('UPDATE subscribers SET lang=? WHERE id=?').bind(L,g.id).run();await tgApi(token,'sendMessage',{chat_id:chatId,...extra,text:LANG_OK[L]});}else await tgApi(token,'sendMessage',{chat_id:chatId,...extra,text:LANG_USE.zh+' · '+LANG_USE.ja+' · '+LANG_USE.en});}
  else if(cmd==='/topics'){const nb=normBoards(text.split(/\s+/).slice(1).join(',').split(',').map(s=>s.trim()).filter(Boolean));if(nb.length){await c.env.DB.prepare('UPDATE subscribers SET boards=? WHERE id=?').bind(JSON.stringify(nb),g.id).run();await tgApi(token,'sendMessage',{chat_id:chatId,...extra,text:'\u2705 '+nb.join(', ')});}else await tgApi(token,'sendRichMessage',{chat_id:chatId,...extra,rich_message:{markdown:'可选主题：'+subTopics()}});}
  else if(cmd==='/stop'){await c.env.DB.prepare('UPDATE subscribers SET active=0 WHERE id=?').bind(g.id).run();await tgApi(token,'sendMessage',{chat_id:chatId,...extra,text:'已暂停 · 再次 @我 即可恢复'});}
  else if(cmd==='/delete'){await c.env.DB.prepare('DELETE FROM subscribers WHERE id=?').bind(g.id).run();await tgApi(token,'sendMessage',{chat_id:chatId,...extra,text:'已删除。'});}
  else{await c.env.DB.prepare('UPDATE subscribers SET active=1,chat_title=?,lang=lang WHERE id=?').bind(chatTitle,g.id).run();await tgApi(token,'sendMessage',{chat_id:chatId,...extra,text:'✅ 已设置。以后每天 08:00 JST 我会在这个话题里推送每日简报。\n可调整：/time 8 · /topics ai,crypto · /stop · /delete'});}
  return c.json({ok:true});
}
sub=await c.env.DB.prepare('SELECT * FROM subscribers WHERE owner_user_id=?').bind(fromId).first() as Record<string,any>|null;
if(!sub){if(cmd!=='/start'&&cmd!=='/brief'&&cmd!=='/help')return c.json({ok:true});const id=crypto.randomUUID();await c.env.DB.prepare('INSERT INTO subscribers (id,secret,token,bot_username,chat_id,owner_user_id,lang,hour,boards,active,created_at) VALUES (?,?,?,?,?,?,?,?,?,1,?)').bind(id,newSecret(),'Antist_monitor_bot',chatId,fromId,'zh',8,'[]',new Date().toISOString()).run();sub=await c.env.DB.prepare('SELECT * FROM subscribers WHERE id=?').bind(id).first() as Record<string,any>;}
else if(chatId!==String(sub.chat_id))await c.env.DB.prepare('UPDATE subscribers SET chat_id=? WHERE id=?').bind(chatId,sub.id).run();
if(cmd==='/start'||cmd==='/help')await tgApi(token,'sendRichMessage',{chat_id:chatId,rich_message:{markdown:subHelp(sub,cmd==='/start')}});
else if(cmd==='/brief')await sendSubscriber(c.env,{...sub,chat_id:chatId,token},new Date(Date.now()+9*3600000).toISOString().slice(0,10));
else if(cmd==='/lang'){const L=String(arg||'').toLowerCase();if(LANGS.includes(L)){await c.env.DB.prepare('UPDATE subscribers SET lang=? WHERE id=?').bind(L,sub.id).run();await tgApi(token,'sendMessage',{chat_id:chatId,text:LANG_OK[L]});}else await tgApi(token,'sendMessage',{chat_id:chatId,text:LANG_USE.zh+' · '+LANG_USE.ja+' · '+LANG_USE.en});}
else if(cmd==='/topics'){const nb=normBoards(text.split(/\s+/).slice(1).join(',').split(',').map(s=>s.trim()).filter(Boolean));if(nb.length){await c.env.DB.prepare('UPDATE subscribers SET boards=? WHERE id=?').bind(JSON.stringify(nb),sub.id).run();await tgApi(token,'sendMessage',{chat_id:chatId,text:'\u2705 '+nb.join(', ')});}else await tgApi(token,'sendRichMessage',{chat_id:chatId,rich_message:{markdown:'可选主题：'+subTopics()}});}
else if(cmd==='/time'){const h=Number(arg);if(Number.isInteger(h)&&h>=0&&h<=23){await c.env.DB.prepare('UPDATE subscribers SET hour=? WHERE id=?').bind(h,sub.id).run();await tgApi(token,'sendMessage',{chat_id:chatId,text:'\u23f0 每天约 '+h+':41 JST 推送'});}else await tgApi(token,'sendMessage',{chat_id:chatId,text:'用法: /time 8'});}
else if(cmd==='/stop'){await c.env.DB.prepare('UPDATE subscribers SET active=0 WHERE id=?').bind(sub.id).run();await tgApi(token,'sendMessage',{chat_id:chatId,text:'已暂停 · /start 恢复'});}
else if(cmd==='/delete'){await c.env.DB.prepare('DELETE FROM subscribers WHERE id=?').bind(sub.id).run();await tgApi(token,'sendMessage',{chat_id:chatId,text:'已删除。可随时 /start 重新订阅。'});}
}else{
sub=await c.env.DB.prepare('SELECT * FROM subscribers WHERE secret=?').bind(rawSecret).first() as Record<string,any>|null;if(!sub)return c.json({ok:true});
if(sub.webhook_secret&&c.req.header('x-telegram-bot-api-secret-token')!==String(sub.webhook_secret))return c.json({ok:true});
if(uid&&Number(sub.last_update_id||0)>=uid)return c.json({ok:true});if(uid)await c.env.DB.prepare('UPDATE subscribers SET last_update_id=? WHERE id=?').bind(uid,sub.id).run();
token=String(sub.token);
if(!sub.chat_id){if(cmd==='/start'&&arg&&arg.toUpperCase()===String(sub.pair_code||'')){await c.env.DB.prepare('UPDATE subscribers SET chat_id=?,owner_user_id=?,active=1 WHERE id=?').bind(chatId,fromId,sub.id).run();await tgApi(token,'sendRichMessage',{chat_id:chatId,rich_message:{markdown:subHelp({...sub,chat_id:chatId,owner_user_id:fromId},true)}});}else{await tgApi(token,'sendMessage',{chat_id:chatId,text:'请发送  /start '+String(sub.pair_code||'')+'  完成绑定'});}return c.json({ok:true});}
if(chatId!==String(sub.chat_id)||fromId!==String(sub.owner_user_id))return c.json({ok:true});
if(cmd==='/start'||cmd==='/help')await tgApi(token,'sendRichMessage',{chat_id:chatId,rich_message:{markdown:subHelp(sub,cmd==='/start')}});
else if(cmd==='/brief')await sendSubscriber(c.env,{...sub,chat_id:chatId},new Date(Date.now()+9*3600000).toISOString().slice(0,10));
else if(cmd==='/lang'){const L=String(arg||'').toLowerCase();if(LANGS.includes(L)){await c.env.DB.prepare('UPDATE subscribers SET lang=? WHERE id=?').bind(L,sub.id).run();await tgApi(token,'sendMessage',{chat_id:chatId,text:LANG_OK[L]});}else await tgApi(token,'sendMessage',{chat_id:chatId,text:LANG_USE.zh+' · '+LANG_USE.ja+' · '+LANG_USE.en});}
else if(cmd==='/topics'){const nb=normBoards(text.split(/\s+/).slice(1).join(',').split(',').map(s=>s.trim()).filter(Boolean));if(nb.length){await c.env.DB.prepare('UPDATE subscribers SET boards=? WHERE id=?').bind(JSON.stringify(nb),sub.id).run();await tgApi(token,'sendMessage',{chat_id:chatId,text:'\u2705 '+nb.join(', ')});}else await tgApi(token,'sendRichMessage',{chat_id:chatId,rich_message:{markdown:'可选主题：'+subTopics()}});}
else if(cmd==='/time'){const h=Number(arg);if(Number.isInteger(h)&&h>=0&&h<=23){await c.env.DB.prepare('UPDATE subscribers SET hour=? WHERE id=?').bind(h,sub.id).run();await tgApi(token,'sendMessage',{chat_id:chatId,text:'\u23f0 每天约 '+h+':41 JST 推送'});}else await tgApi(token,'sendMessage',{chat_id:chatId,text:'用法: /time 8'});}
else if(cmd==='/stop'){await c.env.DB.prepare('UPDATE subscribers SET active=0 WHERE id=?').bind(sub.id).run();await tgApi(token,'sendMessage',{chat_id:chatId,text:'已暂停 · /start 恢复'});}
}
}catch{}return c.json({ok:true});});
app.post('/api/ingest',async c=>{
  const actual=c.req.header('Authorization')||'';const expected=`Bearer ${c.env.RADAR_INGEST_TOKEN||''}`;
  const hash=async(v:string)=>new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(v)));
  const [a,b]=await Promise.all([hash(actual),hash(expected)]);let diff=0;for(let i=0;i<a.length;i++)diff|=a[i]^b[i];
  if(!c.env.RADAR_INGEST_TOKEN||diff!==0)return c.json({ok:false},401);
  if(Number(c.req.header('Content-Length')||0)>700000)return c.json({ok:false},413);
  let s:Snapshot;try {const reader=c.req.raw.body?.getReader();if(!reader)return c.json({ok:false},400);const decoder=new TextDecoder();let raw='',size=0;for(;;){const {done,value}=await reader.read();if(done)break;size+=value.byteLength;if(size>700000){await reader.cancel();return c.json({ok:false},413);}raw+=decoder.decode(value,{stream:true});}raw+=decoder.decode();s=publicSnapshot(JSON.parse(raw));}catch{return c.json({ok:false,reason:'invalid public payload'},400);}
  if(Math.abs(Date.now()-Date.parse(s.generatedAt))>7200000)return c.json({ok:false,reason:'stale publication'},409);
  const current=await c.env.MONITOR.get<Snapshot>(KEY,'json');
  if(current&&Date.parse(current.generatedAt)>Date.parse(s.generatedAt))return c.json({ok:false,reason:'out of order'},409);
  const key=`snapshots/${s.generatedAt.slice(0,10)}/${s.id}.json`;
  for(const f of (s.forecasts||[])){await c.env.DB.prepare('INSERT OR IGNORE INTO forecasts (id,created_at,due_at,symbol,baseline,direction,probability,claim_json,rationale_json,evidence_json) VALUES (?,?,?,?,?,?,?,?,?,?)').bind(f.id,f.createdAt,f.dueAt,f.symbol,f.baseline,f.direction,f.probability,JSON.stringify(f.claim),JSON.stringify(f.rationale),JSON.stringify(f.evidence)).run();}
  for(const f of (s.forecasts||[])){const r=await c.env.DB.prepare('SELECT * FROM forecasts WHERE id=?').bind(f.id).first();if(r){f.createdAt=String(r.created_at);f.dueAt=String(r.due_at);f.symbol=String(r.symbol);f.baseline=Number(r.baseline);f.direction=r.direction==='above'?'above':'below';f.probability=Number(r.probability);f.claim=JSON.parse(String(r.claim_json));f.rationale=JSON.parse(String(r.rationale_json));f.evidence=JSON.parse(String(r.evidence_json));}}
  await c.env.ARCHIVE.put(key,JSON.stringify(s),{httpMetadata:{contentType:'application/json'}});
  await settle(c.env,s);
  const nowIso=new Date().toISOString();
  const evStmts=(s.events||[]).map(e=>c.env.DB.prepare('INSERT INTO events (id,source,category,url,published_at,first_seen,last_seen,stage,deadline_at,change,title_json,summary_json,audience_json,action_json,unknowns_json,evidence,score) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET last_seen=excluded.last_seen,source=excluded.source,category=excluded.category,url=excluded.url,published_at=excluded.published_at,stage=excluded.stage,deadline_at=excluded.deadline_at,change=excluded.change,title_json=excluded.title_json,summary_json=excluded.summary_json,audience_json=excluded.audience_json,action_json=excluded.action_json,unknowns_json=excluded.unknowns_json,evidence=excluded.evidence,score=excluded.score').bind(e.id,e.source,e.category,e.url,e.publishedAt||null,nowIso,nowIso,e.stage||null,e.deadlineAt||null,e.change||null,JSON.stringify(e.title),JSON.stringify(e.summary),JSON.stringify(e.audience),JSON.stringify(e.action),JSON.stringify(e.unknowns),e.evidence,e.score||0));
  if(evStmts.length)await c.env.DB.batch(evStmts);
  await c.env.DB.prepare('INSERT OR IGNORE INTO sweeps (id,fetched_at,published_at,source_count,healthy_count,event_count,archive_key) VALUES (?,?,?,?,?,?,?)').bind(s.id,s.generatedAt,new Date().toISOString(),s.sources.length,s.sources.filter(x=>['ok','quiet'].includes(x.status)).length,s.events.length,key).run();
  try{await c.env.MONITOR.put('radar:version',s.generatedAt);}catch{}return c.json({ok:true,id:s.id,archived:true});
});
app.get('/subscribe',c=>c.redirect('/zh#subscribe',302));
app.get('/:locale/c/:category',async c=>{
const l=c.req.param('locale') as Locale;const cat=c.req.param('category');
if(!languages.includes(l)||!(cat==='all'||(BOARDS as readonly string[]).includes(cat)))return c.notFound();
const w=words[l] as unknown as Record<string,string>;
const page=Math.max(1,Number(c.req.query('page'))||1);const per=40;const off=(page-1)*per;
const q=(c.req.query('q')||'').trim().slice(0,60);
const conds:string[]=[];const binds:(string|number)[]=[];
if(cat!=='all'){conds.push('category=?');binds.push(cat);}
if(q){conds.push("instr(lower(title_json||' '||coalesce(summary_json,'')||' '||coalesce(audience_json,'')||' '||coalesce(action_json,'')||' '||coalesce(unknowns_json,'')||' '||evidence),lower(?))>0");binds.push(q);}
const where=conds.length?(' WHERE '+conds.join(' AND ')):'';
const res=await c.env.DB.prepare('SELECT * FROM events'+where+' ORDER BY COALESCE(published_at,first_seen) DESC LIMIT ? OFFSET ?').bind(...binds,per+1,off).all();
const rows=(res.results||[]);const hasMore=rows.length>per;const events=rows.slice(0,per).map(rowToEvent);
const cnt=await c.env.DB.prepare('SELECT COUNT(*) n FROM events'+where).bind(...binds).first() as {n?:number}|null;
const total=Number(cnt?.n||events.length);
const label=cat==='all'?w.archive:(w[cat]||cat);
const qs=(p:number)=>{const sp=new URLSearchParams();if(p>1)sp.set('page',String(p));if(q)sp.set('q',q);const s=sp.toString();return `/${l}/c/${cat}`+(s?'?'+s:'');};
c.header('Cache-Control','no-store');c.header('Content-Language',l);
return c.html(<html lang={l}>{pageHead(l,`/${l}/c/${cat}`)}<body><SiteHeader l={l} w={w} cat={cat}/><main class="mx-auto max-w-6xl px-4 md:px-6 pb-20">
<div class="pt-8"><div class="inline-flex items-center gap-1 rounded-lg border bg-card p-1 shadow-sm"><a href={`/${l}`} class="btn btn-ghost btn-sm">← {w.back}</a></div></div>
<div class="mt-4 mb-6 flex flex-wrap items-end justify-between gap-4"><div><p class="text-[10px] uppercase tracking-widest text-muted-foreground mb-1.5">{w.archive}</p><h1 class="text-3xl font-bold tracking-tight">{label}</h1></div><span class="text-xs tabular-nums text-muted-foreground">{String(total).padStart(2,'0')} · {w.page} {page}</span><button data-speak class="btn btn-outline btn-sm">🔊 {w.listen}</button></div>
<form method="get" action={`/${l}/c/${cat}`} class="mb-4 flex flex-wrap gap-2"><input type="search" name="q" value={q} class="input h-9 w-full sm:w-80" placeholder={w.search}/><button class="btn btn-outline btn-sm">{w.search}</button></form>
<div class="mb-8 inline-flex flex-wrap items-center gap-1 rounded-lg bg-muted p-1"><a href={`/${l}/c/all`} class={`tab ${cat==='all'?'tab-active':''}`}>{w.archive}</a>{BOARDS.map(b=><a href={`/${l}/c/${b}`} class={`tab ${b===cat?'tab-active':''}`}>{w[b]}</a>)}</div>
{events.length?<div class="grid md:grid-cols-2 gap-4">{events.map((e,i)=><EventCard e={e} index={i} l={l} w={w}/>)}</div>:<div class="card p-12 text-center text-sm text-muted-foreground">{w.noresults}</div>}
<div class="mt-10 flex items-center justify-between gap-4"><div>{page>1?<a href={qs(page-1)} class="btn btn-outline btn-sm">← {w.newer}</a>:null}</div><div>{hasMore?<a href={qs(page+1)} class="btn btn-outline btn-sm">{w.older} →</a>:null}</div></div>
</main><SiteFooter w={w}/></body></html>);});
app.get('/:locale/ledger',async c=>{const l=c.req.param('locale') as Locale;if(!languages.includes(l))return c.notFound();const w=words[l] as unknown as Record<string,string>;const page=Math.max(1,Number(c.req.query('page'))||1);const per=10;const off=(page-1)*per;const res=await c.env.DB.prepare('SELECT * FROM forecasts ORDER BY created_at DESC LIMIT ? OFFSET ?').bind(per+1,off).all();const rows=(res.results||[]);const hasMore=rows.length>per;const list=rows.slice(0,per);const q2=(p:number)=>`/${l}/ledger${p>1?`?page=${p}`:''}`;c.header('Cache-Control','no-store');c.header('Content-Language',l);return c.html(<html lang={l}>{pageHead(l,`/${l}/ledger`)}<body><SiteHeader l={l} w={w}/><main class="mx-auto max-w-6xl px-4 md:px-6 pb-20"><div class="pt-8"><div class="inline-flex items-center gap-1 rounded-lg border bg-card p-1 shadow-sm"><a href={`/${l}`} class="btn btn-ghost btn-sm">← {w.back}</a></div></div><div class="mt-4 mb-8 flex flex-wrap items-end justify-between gap-4"><div><p class="text-[10px] uppercase tracking-widest text-muted-foreground mb-1.5">On the record</p><h1 class="text-3xl font-bold tracking-tight">{w.ledger}</h1><p class="text-sm text-muted-foreground mt-1">{w.before}</p></div><div class="flex items-center gap-3"><span class="text-xs tabular-nums text-muted-foreground">{w.page} {page}</span><button data-speak class="btn btn-outline btn-sm">🔊 {w.listen}</button></div></div>{list.length?<div class="grid md:grid-cols-2 gap-4">{list.map(r=><ForecastCard r={r} l={l} w={w}/>)}</div>:<div class="card p-12 text-center text-sm text-muted-foreground">{w.noForecast}</div>}<div class="mt-10 flex items-center justify-between gap-4"><div>{page>1?<a href={q2(page-1)} class="btn btn-outline btn-sm">← {w.newer}</a>:null}</div><div>{hasMore?<a href={q2(page+1)} class="btn btn-outline btn-sm">{w.older} →</a>:null}</div></div></main><SiteFooter w={w}/></body></html>);});
app.get('/:locale',async c=>{
  const l=c.req.param('locale') as Locale;if(!languages.includes(l))return c.notFound();
  const __ver=await c.env.MONITOR.get('radar:version')||'0';const __cache=(caches as unknown as {default:{match(r:Request):Promise<Response|undefined>;put(r:Request,res:Response):Promise<void>}}).default;const __ck=new Request(`${ORIGIN}/__ssr/${l}?v=${encodeURIComponent(__ver)}`,{method:'GET'});try{const __hit=await __cache.match(__ck);if(__hit){const __r=new Response(__hit.body,__hit);__r.headers.set('Cache-Control','no-store');return __r;}}catch{}const w=words[l];const s=await latestSnapshot(c.env);const rows=await ledger(c.env.DB);
  const agg=await c.env.DB.prepare('SELECT category, COUNT(*) n FROM events GROUP BY category').all();
  const countMap=new Map((agg.results||[]).map(r=>[String(r.category),Number(r.n)]));
  const totalEvents=(agg.results||[]).reduce((a,r)=>a+Number(r.n),0);
  const stale=!s||Date.now()-Date.parse(s.generatedAt)>150*60000;
  const healthy=s?.sources.filter(x=>['ok','quiet'].includes(x.status)).length||0;
  const strip=(s?.markets.filter(q=>STRIP.includes(q.symbol))||[]);
  c.header('Cache-Control','no-store');c.header('Content-Language',l);
  const __resp=await c.html(<html lang={l}><head><meta charset="utf-8"/><meta name="viewport" content="width=device-width,initial-scale=1"/><title>{titles[l]}</title><meta name="description" content={descriptions[l]}/><link rel="canonical" href={`${ORIGIN}/${l}`}/>{languages.map(lang=><link rel="alternate" hreflang={lang} href={`${ORIGIN}/${lang}`}/>)}<link rel="alternate" hreflang="x-default" href={`${ORIGIN}/en`}/><meta property="og:title" content={titles[l]}/><meta property="og:description" content={descriptions[l]}/><meta property="og:url" content={`${ORIGIN}/${l}`}/><meta property="og:type" content="website"/><meta property="og:image" content={`${ORIGIN}/og.png`}/><meta property="og:image:width" content="1200"/><meta property="og:image:height" content="630"/><meta property="og:image:alt" content="Antist Radar"/><meta name="twitter:card" content="summary_large_image"/><meta name="twitter:title" content={titles[l]}/><meta name="twitter:description" content={descriptions[l]}/><meta name="twitter:image" content={`${ORIGIN}/og.png`}/><meta name="theme-color" content="#0a0a0b"/><link rel="icon" type="image/png" sizes="512x512" href="/favicon-512.png"/><link rel="icon" type="image/png" sizes="32x32" href="/favicon-32.png"/><link rel="apple-touch-icon" href="/apple-touch-icon.png"/><link rel="stylesheet" href="/style.css"/>{html`<script>try{if((localStorage.getItem('radar-theme')||'dark')==='dark')document.documentElement.classList.add('dark')}catch{}</script>`}<script src="/app.js" defer/></head>
  <body><header class="sticky top-0 z-40 w-full border-b bg-background/80 backdrop-blur supports-[backdrop-filter]:bg-background/60"><div class="mx-auto max-w-6xl h-16 px-4 md:px-6 flex items-center justify-between gap-4"><a href={`/${l}`} class="flex items-center gap-2 font-semibold tracking-tight"><span class="logo-icon"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="1.7" fill="currentColor" stroke="none"/><path d="M12 12 19 5"/><path d="M5.5 12a6.5 6.5 0 0 1 6.5-6.5"/><path d="M8.5 12a3.5 3.5 0 0 1 3.5-3.5"/><path d="M2.5 12a9.5 9.5 0 0 1 9.5-9.5" opacity=".5"/></svg></span><span>ANTIST<span class="text-muted-foreground font-normal"> / RADAR</span></span></a><nav class="hidden md:flex items-center gap-1"><a href="#signals" class="navlink">{w.overview}</a><a href="#markets" class="navlink">{w.markets}</a><a href="#ledger" class="navlink">{w.ledger}</a><a href="#sources" class="navlink">{w.sources}</a></nav><div class="flex items-center gap-2"><div class="flex items-center rounded-lg bg-muted p-1">{languages.map(lang=><a href={`/${lang}`} class={`tab px-2.5 py-1 text-xs ${lang===l?'tab-active':''}`}>{lang.toUpperCase()}</a>)}</div><button data-theme class="btn btn-ghost btn-icon relative" aria-label="Toggle theme"><svg class="h-4 w-4 rotate-0 scale-100 transition-all dark:-rotate-90 dark:scale-0" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="4"/><path d="M12 2v2M12 20v2M4.93 4.93l1.41 1.41M17.66 17.66l1.41 1.41M2 12h2M20 12h2M6.34 17.66l-1.41 1.41M19.07 4.93l-1.41 1.41"/></svg><svg class="absolute inset-0 m-auto h-4 w-4 rotate-90 scale-0 transition-all dark:rotate-0 dark:scale-100" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 3a6 6 0 0 0 9 9 9 9 0 1 1-9-9Z"/></svg></button></div></div></header>
  <main class="mx-auto max-w-6xl px-4 md:px-6 pb-16"><section class="py-12 md:py-16 grid lg:grid-cols-[1.4fr_1fr] gap-8 items-start"><div><span class="badge badge-secondary mb-5 gap-1.5">{(stale?<span class="inline-block h-2 w-2 rounded-full bg-down"/>:<span class="live-dot inline-block h-2 w-2 rounded-full bg-up"/>)} {w.tag}</span><h1 class="text-4xl md:text-5xl lg:text-6xl font-bold tracking-tight leading-[1.06]">{w.hero}<br/><span class="text-muted-foreground">{w.sub}</span></h1><p class="mt-5 max-w-xl text-muted-foreground leading-relaxed">{w.intro}</p></div><div class="card p-6"><div class="flex items-center justify-between text-xs text-muted-foreground mb-3"><span class="uppercase tracking-wide">{w.brief}</span><span class="tabular-nums">{s?formatDate(s.generatedAt,l):'—'}</span></div><p class="text-base leading-relaxed">{s?.digest[l]||w.empty}</p><p class="text-[11px] text-muted-foreground mt-4">{w.generated}</p></div></section>
  <section id="markets" class="mb-12"><div class="card p-4 md:p-5"><div class="flex flex-wrap items-center justify-between gap-3 mb-4"><div class="flex items-center gap-2"><h2 class="text-sm font-semibold tracking-tight">{w.markets}</h2><span class="badge badge-outline gap-1.5 text-[10px]"><span class="live-dot inline-block h-1.5 w-1.5 rounded-full bg-up"></span>LIVE</span><span data-markets-status class="text-[11px] text-muted-foreground"></span></div><div class="flex items-center gap-2"><div class="relative"><input data-markets-search class="input h-8 w-44 text-xs" placeholder={w.addSymbol} autocomplete="off"/><div data-markets-suggest class="absolute right-0 top-9 z-50 hidden w-72 overflow-hidden rounded-md border bg-popover text-popover-foreground shadow-md"></div></div><button data-markets-done class="btn btn-primary btn-sm hidden">{w.done}</button><button data-markets-edit class="btn btn-outline btn-sm">{w.editLayout}</button></div></div><div data-markets class="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 gap-2">{strip.map(q=><a href={q.source} target="_blank" rel="noopener noreferrer" class="market-tile"><div class="text-[11px] font-medium text-muted-foreground truncate">{q.name}</div><div class="flex items-baseline justify-between gap-2"><span class="text-lg font-semibold tabular-nums">{q.price.toLocaleString(l,{maximumFractionDigits:2})}</span><span class={`text-xs font-medium tabular-nums ${q.changePct>=0?'text-up':'text-down'}`}>{q.changePct>=0?'+':''}{q.changePct}%</span></div></a>)}</div><p class="text-[11px] text-muted-foreground mt-3 hidden md:block">{w.hint}</p></div></section>
  <section id="signals" class="mb-5"><div class="flex flex-wrap items-center justify-between gap-3 mb-4"><h2 class="text-xl font-semibold tracking-tight">{w.signals} <span class="text-sm text-muted-foreground tabular-nums">{String(totalEvents).padStart(2,'0')}</span></h2><div class="flex items-center gap-2"><input data-search type="search" class="input h-9 w-full sm:w-64" placeholder={w.search}/><button data-boards-done class="btn btn-primary btn-sm hidden">{w.done}</button><button data-boards-edit class="btn btn-outline btn-sm">{w.editBoards}</button><button data-speak class="btn btn-outline btn-sm">🔊 {w.listen}</button></div></div><div data-board-chips class="hidden mt-3"><div class="inline-flex flex-wrap items-center gap-1 rounded-lg bg-muted p-1"><span class="tab opacity-60 pointer-events-none">{w.all}</span>{BOARDS.map(b=><button data-chip={b} class="tab cursor-move">{w[b]}</button>)}</div></div><p class="text-[11px] text-muted-foreground hidden md:block">{w.bhint}</p></section>
  <div data-boards>{BOARDS.map(b=>{const list=(s?.events||[]).filter(e=>e.category===b).sort((x,y)=>(y.score||0)-(x.score||0)).slice(0,3);return <section id={`board-${b}`} data-board={b} data-board-section={b} class="mb-10"><div class="flex items-center justify-between mb-4"><h3 class="text-lg font-semibold tracking-tight"><span data-board-handle class="hidden cursor-move text-muted-foreground mr-1">⠿</span><a href={`/${l}/c/${b}`} class="no-underline">{w[b]}</a> <span class="text-xs text-muted-foreground tabular-nums">{String(countMap.get(b)||0).padStart(2,'0')}</span></h3><div class="flex items-center gap-1"><button data-board-hide={b} class="btn btn-ghost btn-sm hidden" title="hide/show">◌</button><a href={`/${l}/c/${b}`} class="btn btn-outline btn-sm">{w.more} →</a></div></div>{list.length?<div class="grid md:grid-cols-2 lg:grid-cols-3 gap-3">{list.map((e,i)=><EventCard e={e} index={i} l={l} w={w}/>)}</div>:<p class="text-sm text-muted-foreground">{w.noresults}</p>}</section>;})}</div>
  <p data-no-results hidden class="py-12 text-center text-muted-foreground">{w.noresults}</p>
  <section id="ledger" class="py-12 border-t"><div class="mb-6 flex items-start justify-between gap-4"><div><p class="text-[10px] uppercase tracking-widest text-muted-foreground mb-2">On the record</p><h2 class="text-xl font-semibold tracking-tight">{w.ledger}</h2><p class="text-sm text-muted-foreground mt-1">{w.before}</p></div><a href={`/${l}/ledger`} class="btn btn-outline btn-sm shrink-0">{w.more} →</a></div><div class="grid md:grid-cols-2 gap-4">{rows.length?rows.slice(0,10).map(r=><ForecastCard r={r} l={l} w={w}/>):<p class="text-sm text-muted-foreground">{w.noForecast}</p>}</div></section>
  <section id="sources" class="py-12 border-t grid md:grid-cols-[1fr_2fr] gap-8"><div><h2 class="text-xl font-semibold tracking-tight">{w.sources}</h2><p class="text-4xl font-semibold tabular-nums mt-3">{healthy}<span class="text-xl text-muted-foreground"> / {s?.sources.length||0}</span></p><p class="text-xs text-muted-foreground mt-1">{w.healthy}</p></div><div class="grid sm:grid-cols-3 gap-x-4">{s?.sources.map(source=><a href={source.url} target="_blank" rel="noopener noreferrer" class="flex justify-between gap-3 border-b py-2.5 text-xs"><span class="truncate">{source.name}</span><span class={['ok','quiet'].includes(source.status)?'text-up':'text-muted-foreground'}>{source.status}</span></a>)}</div></section>
  <section id="subscribe" class="py-12 border-t"><div class="card p-6 md:p-8 grid md:grid-cols-[1.2fr_1fr] gap-8 items-center"><div><h2 class="text-xl font-semibold tracking-tight">{w.subscribe}</h2><p class="text-sm text-muted-foreground mt-2 leading-relaxed">{w.subintro}</p><p class="text-xs text-muted-foreground mt-4 leading-relaxed">{w.subprivacy}</p></div><div class="flex flex-col gap-3"><a href="https://t.me/Antist_monitor_bot" target="_blank" rel="noopener" class="btn btn-primary w-full">{w.subopen} ↗</a><p class="text-xs text-muted-foreground">{w.subcmd}</p></div></div></section>
  <footer class="border-t py-10 grid md:grid-cols-2 gap-8"><div><p class="text-sm font-semibold tracking-tight">ANTIST / RADAR.</p><p class="text-xs text-muted-foreground mt-3">Japan & the world. Independently observed.</p><p class="text-xs text-muted-foreground mt-4">© {new Date().getFullYear()} Antist · All rights reserved.</p><a class="text-xs text-muted-foreground underline mt-2 inline-block" href="https://github.com/Antisubmissivist/antist-radar">Source code · AGPL-3.0</a></div><div><h2 class="text-xs font-semibold mb-2">{w.method}</h2><p class="text-xs text-muted-foreground leading-relaxed">{w.methodText}</p></div></footer><div data-toast class="pointer-events-none fixed bottom-6 right-6 z-[60] flex flex-col gap-2 items-end"></div></main></body></html>);try{c.executionCtx.waitUntil(__cache.put(__ck,__resp.clone()));}catch{}return __resp;
});
app.onError((err,c)=>{console.error('worker-error: '+((err&&(err as Error).stack)||String(err)));return c.json({error:'Temporarily unavailable'},503);});
export default {fetch:app.fetch,async scheduled(event:ScheduledController,env:Bindings){const s=await latestSnapshot(env);if(!s||Date.now()-Date.parse(s.generatedAt)>50*60000){console.log(JSON.stringify({event:'sweep-dispatch',...(await dispatchSweep(env))}));}if(s){await settle(env,s);}
try{console.log(JSON.stringify({event:'retention',...(await retain(env))}));}catch(e){console.log(JSON.stringify({event:'retention-error',error:String(e)}));}
try{const jstHour=new Date(event.scheduledTime+9*3600000).getUTCHours();const date=new Date(event.scheduledTime+9*3600000).toISOString().slice(0,10);const due=await env.DB.prepare('SELECT * FROM subscribers WHERE active=1 AND hour=? AND (last_sent IS NULL OR last_sent<>?) LIMIT 100').bind(jstHour,date).all();for(const sub of (due.results||[])){try{const r=await sendSubscriber(env,sub as Record<string,unknown>,date) as {ok?:boolean;description?:string};if(r&&r.ok){await env.DB.prepare('UPDATE subscribers SET last_sent=? WHERE id=?').bind(date,(sub as Record<string,unknown>).id).run();}else{console.log(JSON.stringify({event:'subscriber-send-fail',id:(sub as Record<string,unknown>).id,detail:r?.description}));}}catch(e){console.log(JSON.stringify({event:'subscriber-fail',id:(sub as Record<string,unknown>).id,error:String(e)}));}}}catch(e){console.log(JSON.stringify({event:'subscribers-error',error:String(e)}));}}};
