import {Hono} from 'hono';
import {html} from 'hono/html';
import {publicSnapshot,resolveForecast} from '../../engine/lib/radar-contract.mjs';
import {ORIGIN,languages,titles,descriptions,type Locale} from './seo';
import {sendDigest} from './delivery';
import {getMarkets,setWatchlist} from './markets';
type Bindings=Env & {RADAR_INGEST_TOKEN:string;TELEGRAM_BOT_TOKEN?:string;TELEGRAM_CHAT_ID?:string};
type Snapshot=ReturnType<typeof publicSnapshot>;
const app=new Hono<{Bindings:Bindings}>();
const KEY='radar:public';
const BOARDS=['ai','japan-residence','japan-life','geopolitics','crypto','stocks'] as const;
const words={
  en:{tag:'INDEPENDENT INTELLIGENCE',hero:'Know what changed.',sub:'Decide what matters.',intro:'A considered view of Japan and the world. Evidence first. Useful signals. Predictions that stay on the record.',brief:'The briefing',signals:'Signals worth your attention',all:'All signals',tools:'Tools & work',policy:'Rules & policy',opportunity:'Opportunities',living:'Everyday life',security:'Digital safety',world:'The wider world',ai:'AI',"japan-residence":'Residency & rules',"japan-life":'Japan · everyday life',geopolitics:'Geopolitics',crypto:'Crypto',stocks:'Stocks',ledger:'Prediction ledger',sources:'Source health',updated:'Updated',stale:'Data is stale. Check the original before acting.',empty:'The first verified briefing is being prepared.',search:'Search this briefing',audience:'Who it affects',action:'Next step',unknowns:'What remains unknown',evidence:'Read the evidence',original:'Original source',forecast:'An accountable hypothesis',disclaimer:'Experimental forecast, not investment advice. The first fresh observation after the deadline determines the result.',due:'Resolves after',baseline:'Baseline',prob:'Probability',open:'Open',hit:'Hit',miss:'Miss',unresolved:'Unresolved',noForecast:'No forecast has been published yet.',noresults:'No matching signals.',method:'Method',methodText:'Public sources are checked, changes are deduplicated, and native editions are written from the same evidence. Selection is editorial and bounded, not an exhaustive feed. Unknown applicability stays unknown. No personal profiles are published.',healthy:'healthy sources',edition:'Edition',history:'Recent collection runs',before:'Published forecasts are immutable. Misses remain visible.',read:'Read the source',generated:'AI-assisted analysis · primary-source verification required',overview:'Overview'},
  ja:{tag:'独立インテリジェンス',hero:'変化を捉える。',sub:'判断につなげる。',intro:'日本と世界を、根拠から読み解く。暮らしに役立つ情報と、結果を検証できる予測を。',brief:'今回の見立て',signals:'注目すべき変化',all:'すべて',tools:'ツール・仕事',policy:'制度・政策',opportunity:'募集・機会',living:'暮らし',security:'デジタル安全',world:'世界情勢',ai:'AI',"japan-residence":'在留・制度',"japan-life":'日本での暮らし',geopolitics:'地政学',crypto:'暗号資産',stocks:'株式',ledger:'予測の記録',sources:'情報源の状態',updated:'更新',stale:'情報が古くなっています。行動の前に原文を確認してください。',empty:'検証済みの初回ブリーフィングを準備中です。',search:'このブリーフィングを検索',audience:'関係する人',action:'次の一歩',unknowns:'未確認の点',evidence:'根拠を確認',original:'一次情報',forecast:'検証可能な仮説',disclaimer:'実験的な予測であり、投資助言ではありません。期限後の最初の新しい観測で判定します。',due:'判定開始',baseline:'基準値',prob:'確率',open:'未決着',hit:'的中',miss:'不的中',unresolved:'判定保留',noForecast:'公開された予測はまだありません。',noresults:'該当する情報はありません。',method:'編集方針',methodText:'公開情報を確認し、変化を重複なく追跡。同じ根拠から各言語で独立した文章を作成します。全件収集ではなく、範囲を定めた編集です。適用条件が不明なら不明と示し、個人の情報は公開しません。',healthy:'正常な情報源',edition:'言語',history:'最近の収集記録',before:'公開した予測は書き換えません。外れた記録も残します。',read:'原文を読む',generated:'AI 支援による分析 · 一次情報で要確認',overview:'概要'},
  zh:{tag:'独立信息雷达',hero:'看见变化。',sub:'形成自己的判断。',intro:'从依据出发，观察日本与世界。发现生活中的可用选择，让每次预判留下可核查的记录。',brief:'本期判断',signals:'值得留意的变化',all:'全部',tools:'工具与工作',policy:'规则与政策',opportunity:'申请与机会',living:'日常生活',security:'数字安全',world:'世界变化',ai:'AI 圈',"japan-residence":'日本在留',"japan-life":'日本生活',geopolitics:'地缘政治',crypto:'加密',stocks:'股票',ledger:'预测记账本',sources:'信源状态',updated:'更新于',stale:'数据已陈旧，采取行动前请核对原文。',empty:'正在准备首份经过核验的简报。',search:'搜索本期简报',audience:'影响谁',action:'最小行动',unknowns:'尚未确认',evidence:'查看依据',original:'原始来源',forecast:'一条可验证的假设',disclaimer:'实验性预测，不构成投资建议。以到期后首次新报价判定结果。',due:'开始结算',baseline:'基准值',prob:'概率',open:'待结算',hit:'命中',miss:'未命中',unresolved:'待核查',noForecast:'尚无已发布预测。',noresults:'没有匹配的信息。',method:'编辑方法',methodText:'核查公开信源、识别变化并去重，从同一组依据分别写成三语内容。这里是有范围的编辑筛选，不是全量信息流。资格不明就保留未知，不公开任何个人匹配资料。',healthy:'健康信源',edition:'语言',history:'近期采集记录',before:'预测发布后保留原文，未命中的记录也不会删除。',read:'阅读原文',generated:'AI 辅助分析 · 行动前请核对一手来源',overview:'概览'}
};
function formatDate(s:string,l:Locale){return new Intl.DateTimeFormat(l==='zh'?'zh-CN':l==='ja'?'ja-JP':'en-GB',{timeZone:'Asia/Tokyo',month:'short',day:'numeric',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(s))+' JST';}
function Badge({children}:{children:unknown}){return <span class="border rule px-2 py-1 text-[10px] font-medium uppercase tracking-widest">{children}</span>}
function Card({children}:{children:unknown}){return <section class="panel border rule p-6 md:p-8">{children}</section>}
function EventCard({e,index,l,w}:{e:Snapshot['events'][number];index:number;l:Locale;w:Record<string,string>}){
  return <article data-event data-category={e.category} class="event-card py-7 border-b rule">
    <div class="flex justify-between items-center mb-4"><div class="flex gap-2 items-center"><span class="number muted text-[10px]">{String(index+1).padStart(2,'0')}</span><Badge>{w[e.category]||e.category}</Badge></div><span class="text-[10px] muted">{e.source}</span></div>
    <a href={e.url} target="_blank" rel="noopener noreferrer" class="no-underline"><h3 class="text-xl font-medium leading-snug tracking-tight">{e.title[l]} <span class="muted text-sm">↗</span></h3></a>
    <p class="text-sm muted leading-relaxed mt-3">{e.summary[l]}</p>
    <div class="border-l-2 border-lime-500 pl-4 mt-5"><p class="text-[10px] font-semibold uppercase tracking-widest mb-1">{w.action}</p><p class="text-sm leading-relaxed">{e.action[l]}</p></div>
    <details class="text-xs muted mt-5"><summary>{w.evidence}</summary><dl class="space-y-3 leading-relaxed"><div><dt class="font-semibold">{w.audience}</dt><dd>{e.audience[l]}</dd></div><div><dt class="font-semibold">{w.unknowns}</dt><dd>{e.unknowns[l]}</dd></div><div><dt class="font-semibold">{w.original}</dt><dd>{e.evidence}</dd></div></dl><a href={e.url} target="_blank" rel="noopener noreferrer" class="inline-block mt-3 underline">{w.read}</a></details>
  </article>;
}
async function ledger(db:D1Database){return (await db.prepare('SELECT * FROM forecasts ORDER BY created_at DESC LIMIT 20').all()).results;}
async function settle(env:Bindings,s:Snapshot){
  const rows=(await env.DB.prepare("SELECT * FROM forecasts WHERE status='open' AND due_at<=? LIMIT 100").bind(new Date().toISOString()).all()).results;
  for(const r of rows){const result=resolveForecast({symbol:r.symbol,baseline:r.baseline,direction:r.direction,dueAt:r.due_at},s.markets);
    if(result)await env.DB.prepare("UPDATE forecasts SET status=?,observed=?,observation_at=?,resolved_at=? WHERE id=? AND status='open'").bind(result.status,result.observed,result.observationAt,result.resolvedAt,r.id).run();}
}
app.use('*',async(c,next)=>{await next();c.header('X-Content-Type-Options','nosniff');c.header('Referrer-Policy','strict-origin-when-cross-origin');c.header('X-Frame-Options','DENY');});
app.get('/',c=>c.redirect('/en',302));
app.get('/robots.txt',c=>c.text(`User-agent: *\nAllow: /\nDisallow: /api/ingest\nSitemap: ${ORIGIN}/sitemap.xml`));
app.get('/sitemap.xml',c=>c.body(`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${languages.map(l=>`<url><loc>${ORIGIN}/${l}</loc></url>`).join('')}</urlset>`,200,{'Content-Type':'application/xml'}));
app.get('/api/public',async c=>{const s=await c.env.MONITOR.get(KEY);c.header('Cache-Control','no-store');return s?c.body(s,200,{'Content-Type':'application/json'}):c.json({status:'pending'},503);});
app.get('/api/ledger',async c=>c.json({forecasts:await ledger(c.env.DB)}));
app.get('/api/markets',async c=>{const m=await getMarkets(c.env);c.header('Cache-Control','no-store');return c.json(m);});
app.post('/api/watchlist',async c=>{const expected=`Bearer ${c.env.RADAR_INGEST_TOKEN||''}`;if(!c.env.RADAR_INGEST_TOKEN||c.req.header('Authorization')!==expected)return c.json({ok:false},401);const body=await c.req.json().catch(()=>null) as {symbols?:unknown}|null;if(!Array.isArray(body?.symbols))return c.json({ok:false,reason:'symbols[] required'},400);const list=(body!.symbols as unknown[]).filter((s):s is {symbol:string;name?:string}=>!!s&&typeof (s as {symbol?:unknown}).symbol==='string').slice(0,30).map(s=>({symbol:String(s.symbol).slice(0,24),name:String(s.name||s.symbol).slice(0,40)}));await setWatchlist(c.env,list);return c.json({ok:true,count:list.length});});
app.post('/api/digest',async c=>{const expected=c.env.RADAR_INGEST_TOKEN;if(!expected||c.req.header('Authorization')!==`Bearer ${expected}`)return c.json({ok:false},401);const s=await c.env.MONITOR.get<Snapshot>(KEY,'json');if(!s)return c.json({status:'pending'},503);return c.json(await sendDigest(c.env,s));});
app.post('/api/ingest',async c=>{
  const actual=c.req.header('Authorization')||'';const expected=`Bearer ${c.env.RADAR_INGEST_TOKEN||''}`;
  const hash=async(v:string)=>new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(v)));
  const [a,b]=await Promise.all([hash(actual),hash(expected)]);let diff=0;for(let i=0;i<a.length;i++)diff|=a[i]^b[i];
  if(!c.env.RADAR_INGEST_TOKEN||diff!==0)return c.json({ok:false},401);
  if(Number(c.req.header('Content-Length')||0)>700000)return c.json({ok:false},413);
  let s:Snapshot;try {const reader=c.req.raw.body?.getReader();if(!reader)return c.json({ok:false},400);const decoder=new TextDecoder();let raw='',size=0;for(;;){const {done,value}=await reader.read();if(done)break;size+=value.byteLength;if(size>700000){await reader.cancel();return c.json({ok:false},413);}raw+=decoder.decode(value,{stream:true});}raw+=decoder.decode();s=publicSnapshot(JSON.parse(raw));}catch{return c.json({ok:false,reason:'invalid public payload'},400);}
  if(Math.abs(Date.now()-Date.parse(s.generatedAt))>7200000)return c.json({ok:false,reason:'stale publication'},409);
  const current=await c.env.MONITOR.get<Snapshot>(KEY,'json');
  if(current&&Date.parse(current.generatedAt)>Date.parse(s.generatedAt))return c.json({ok:false,reason:'out of order'},409);
  const key=`snapshots/${s.generatedAt.slice(0,10)}/${s.id}.json`;
  for(const f of (s.forecasts||[])){await c.env.DB.prepare('INSERT OR IGNORE INTO forecasts (id,created_at,due_at,symbol,baseline,direction,probability,claim_json,rationale_json,evidence_json) VALUES (?,?,?,?,?,?,?,?,?,?)').bind(f.id,f.createdAt,f.dueAt,f.symbol,f.baseline,f.direction,f.probability,JSON.stringify(f.claim),JSON.stringify(f.rationale),JSON.stringify(f.evidence)).run();}
  for(const f of (s.forecasts||[])){const r=await c.env.DB.prepare('SELECT * FROM forecasts WHERE id=?').bind(f.id).first();if(r){f.createdAt=String(r.created_at);f.dueAt=String(r.due_at);f.symbol=String(r.symbol);f.baseline=Number(r.baseline);f.direction=r.direction==='above'?'above':'below';f.probability=Number(r.probability);f.claim=JSON.parse(String(r.claim_json));f.rationale=JSON.parse(String(r.rationale_json));f.evidence=JSON.parse(String(r.evidence_json));}}
  await c.env.ARCHIVE.put(key,JSON.stringify(s),{httpMetadata:{contentType:'application/json'}});
  await settle(c.env,s);
  await c.env.DB.prepare('INSERT OR IGNORE INTO sweeps (id,fetched_at,published_at,source_count,healthy_count,event_count,archive_key) VALUES (?,?,?,?,?,?,?)').bind(s.id,s.generatedAt,new Date().toISOString(),s.sources.length,s.sources.filter(x=>['ok','quiet'].includes(x.status)).length,s.events.length,key).run();
  await c.env.MONITOR.put('radar:ledger',JSON.stringify(await ledger(c.env.DB)));
  await c.env.MONITOR.put(KEY,JSON.stringify(s));return c.json({ok:true,id:s.id,archived:true});
});
app.get('/:locale',async c=>{
  const l=c.req.param('locale') as Locale;if(!languages.includes(l))return c.notFound();
  const w=words[l];const [s,cachedLedger]=await Promise.all([c.env.MONITOR.get<Snapshot>(KEY,'json'),c.env.MONITOR.get<Record<string,unknown>[]>('radar:ledger','json')]);const rows=cachedLedger||[];
  const stale=!s||Date.now()-Date.parse(s.generatedAt)>90*60000;
  const healthy=s?.sources.filter(x=>['ok','quiet'].includes(x.status)).length||0;
  c.header('Cache-Control','no-store');c.header('Content-Language',l);
  return c.html(<html lang={l}><head><meta charset="utf-8"/><meta name="viewport" content="width=device-width,initial-scale=1"/><title>{titles[l]}</title><meta name="description" content={descriptions[l]}/><link rel="canonical" href={`${ORIGIN}/${l}`}/>{languages.map(lang=><link rel="alternate" hreflang={lang} href={`${ORIGIN}/${lang}`}/>)}<link rel="alternate" hreflang="x-default" href={`${ORIGIN}/en`}/><meta property="og:title" content={titles[l]}/><meta property="og:description" content={descriptions[l]}/><meta property="og:url" content={`${ORIGIN}/${l}`}/><meta property="og:type" content="website"/><link rel="stylesheet" href="/style.css"/>{html`<script>try{if((localStorage.getItem('radar-theme')||'dark')==='dark')document.documentElement.classList.add('dark')}catch{}</script>`}<script src="/app.js" defer/></head>
  <body><header class="border-b rule"><div class="max-w-[1440px] mx-auto px-5 md:px-12 h-20 flex items-center justify-between gap-4"><a href={`/${l}`} class="font-black tracking-[-.06em] text-2xl no-underline">ANTIST<span class="font-light"> / </span>RADAR<span class="text-lime-500">.</span></a><nav class="hidden md:flex text-xs gap-7 muted"><a href="#signals">{w.overview}</a><a href="#ledger">{w.ledger}</a><a href="#sources">{w.sources}</a></nav><div class="flex items-center gap-3 text-xs">{languages.map(lang=><a href={`/${lang}`} class={lang===l?'font-bold border-b pb-1':'muted'} aria-current={lang===l?'page':undefined}>{lang.toUpperCase()}</a>)}<button data-theme aria-label="Toggle dark mode" class="border rule px-2 py-1">◐</button></div></div></header>
  <main class="max-w-[1440px] mx-auto px-5 md:px-12"><section class="pt-12 md:pt-20 pb-12 md:pb-16 grid lg:grid-cols-[1.3fr_1fr] gap-10 items-end"><div><p class="text-[10px] tracking-[.2em] font-medium muted mb-6"><span class={`signal mr-2 ${stale?'bad':''}`}/> {w.tag}</p><h1 class="text-4xl md:text-6xl xl:text-7xl font-medium tracking-tight leading-[1.12]">{w.hero}<br/><span class="muted">{w.sub}</span></h1><p class="mt-6 muted max-w-lg text-sm md:text-base leading-relaxed">{w.intro}</p></div><div class="border-l rule pl-6 md:pl-8"><div class="flex justify-between text-xs muted mb-5"><span>{w.brief}</span><span class="number">{s?formatDate(s.generatedAt,l):'—'}</span></div><p class="text-base md:text-lg leading-relaxed">{s?.digest[l]||w.empty}</p><p class="text-[10px] muted mt-5 tracking-wide">{w.generated}</p></div></section>
  {stale&&<div role="status" class="border border-amber-500/40 bg-amber-500/10 px-5 py-3 text-sm mb-8">{w.stale}</div>}
  <section data-markets class="grid grid-cols-2 md:grid-cols-4 border-y rule mb-12">{(s?.markets.filter(q=>['BTC-USD','ETH-USD','SOL-USD','^GSPC','^IXIC','^N225','NVDA','^VIX'].includes(q.symbol))||[]).map(q=><a href={q.source} target="_blank" rel="noopener noreferrer" class="p-5 border-r rule no-underline"><div class="text-[10px] uppercase tracking-widest muted">{q.name}</div><div class="flex justify-between gap-3 items-baseline mt-2"><span class="number text-xl">{q.price.toLocaleString(l,{maximumFractionDigits:2})}</span><span class={`number text-xs ${q.changePct>=0?'text-lime-600 dark:text-lime-400':'text-red-500'}`}>{q.changePct>=0?'+':''}{q.changePct}%</span></div><div class="text-[9px] muted mt-2">Yahoo · {formatDate(q.at,l)}</div></a>)}</section>
  <section id="signals"><div class="flex flex-wrap justify-between items-center gap-5 mb-7"><h2 class="text-2xl font-medium tracking-tight">{w.signals}<span class="number text-xs muted ml-3">{String(s?.events.length||0).padStart(2,'0')}</span></h2><input data-search type="search" placeholder={w.search} aria-label={w.search} class="border rule bg-transparent px-4 py-2 text-sm w-full sm:w-64"/></div><div class="flex flex-wrap gap-2">{(['all',...BOARDS] as string[]).map((cat,i)=><button data-filter={cat} aria-pressed={i===0?'true':'false'} class={`text-[11px] px-3 py-2 border rule ${i===0?'bg-zinc-900 text-white':''}`}>{(w as Record<string,string>)[cat]}</button>)}</div></section>
  {BOARDS.map(b=>{const list=(s?.events||[]).filter(e=>e.category===b);return <section id={`board-${b}`} data-board={b} class="border-t rule py-10"><div class="flex items-baseline justify-between mb-6"><h2 class="text-2xl font-medium tracking-tight">{w[b]}<span class="number text-xs muted ml-3">{String(list.length).padStart(2,'0')}</span></h2></div>{list.length?<div class="grid lg:grid-cols-2 gap-x-10">{list.map((e,i)=><EventCard e={e} index={i} l={l} w={w}/>)}</div>:<p class="muted text-sm">{w.noresults}</p>}</section>;})}
  <p data-no-results hidden class="muted py-12">{w.noresults}</p>
  <section id="ledger" class="py-14 border-t rule mt-8"><div class="mb-7"><p class="text-[10px] tracking-widest muted mb-2">ON THE RECORD</p><h2 class="text-2xl font-medium">{w.ledger}</h2><p class="text-sm muted mt-2">{w.before}</p></div><div class="grid md:grid-cols-2 gap-5">{rows.length?rows.map(r=>{const claim=JSON.parse(String(r.claim_json));const rationale=JSON.parse(String(r.rationale_json));return <Card><div class="flex justify-between mb-5"><Badge>{w[String(r.status) as keyof typeof w]||r.status}</Badge><span class="number text-xs muted">{String(r.created_at).slice(0,10)}</span></div><h3 class="font-medium text-lg leading-relaxed">{claim[l]}</h3><p class="text-sm muted mt-3 leading-relaxed">{rationale[l]}</p><div class="grid grid-cols-2 gap-5 border-t rule mt-6 pt-5"><div><div class="text-[10px] muted">{w.prob}</div><div class="number text-2xl mt-1">{Math.round(Number(r.probability)*100)}%</div></div><div><div class="text-[10px] muted">{w.due}</div><div class="number text-xs mt-2">{formatDate(String(r.due_at),l)}</div></div></div>{r.observed!=null&&<p class="number text-xs mt-4">{r.symbol}: {r.observed} · {r.observation_at}</p>}<p class="text-[10px] muted mt-5 leading-relaxed">{w.disclaimer}</p></Card>}):<p class="muted text-sm">{w.noForecast}</p>}</div></section>
  <section id="sources" class="border-t rule py-12 grid md:grid-cols-[1fr_2fr] gap-10"><div><h2 class="text-2xl font-medium">{w.sources}</h2><p class="number text-4xl mt-5">{healthy}<span class="muted text-xl"> / {s?.sources.length||0}</span></p><p class="text-xs muted mt-2">{w.healthy}</p></div><div class="grid sm:grid-cols-3 gap-x-6">{s?.sources.map(source=><a href={source.url} target="_blank" rel="noopener noreferrer" class="text-xs flex justify-between py-3 border-b rule gap-3"><span>{source.name}</span><span class={['ok','quiet'].includes(source.status)?'text-lime-600 dark:text-lime-400':'text-amber-500'}>{source.status}</span></a>)}</div></section>
  <footer class="border-t rule py-10 grid md:grid-cols-2 gap-8"><div><p class="text-xs font-bold tracking-widest">ANTIST / RADAR.</p><p class="muted text-xs mt-4">Japan & the world. Independently observed.</p><a class="text-xs muted underline mt-3 inline-block" href="https://github.com/Antisubmissivist/antist-radar">Source code · AGPL-3.0</a></div><div><h2 class="text-xs font-semibold mb-3">{w.method}</h2><p class="text-xs muted leading-relaxed">{w.methodText}</p></div></footer></main></body></html>);
});
app.onError((_err,c)=>c.json({error:'Temporarily unavailable'},503));
export default {fetch:app.fetch,async scheduled(event:ScheduledController,env:Bindings){const s=await env.MONITOR.get<Snapshot>(KEY,'json');if(s){await settle(env,s);await env.MONITOR.put('radar:ledger',JSON.stringify(await ledger(env.DB)));if(new Date(event.scheduledTime+9*3600000).getUTCHours()>=8){const result=await sendDigest(env,s,event.scheduledTime);console.log(JSON.stringify({event:'daily-delivery',...result}));}}}};
