import {Hono} from 'hono';
import {html} from 'hono/html';
import {publicSnapshot,resolveForecast} from '../../engine/lib/radar-contract.mjs';
import {ORIGIN,languages,titles,descriptions,type Locale} from './seo';
import {sendDigest} from './delivery';
import {getMarkets,setWatchlist,searchSymbols} from './markets';
type Bindings=Env & {RADAR_INGEST_TOKEN:string;TELEGRAM_BOT_TOKEN?:string;TELEGRAM_CHAT_ID?:string;GH_DISPATCH_TOKEN?:string};
type Snapshot=ReturnType<typeof publicSnapshot>;
const app=new Hono<{Bindings:Bindings}>();
const KEY='radar:public';
const BOARDS=['ai','japan-residence','japan-life','geopolitics','crypto','stocks'] as const;
const STRIP=['BTC-USD','ETH-USD','SOL-USD','^GSPC','^IXIC','^N225','NVDA','^VIX'];
const words={
  en:{tag:'Independent intelligence',hero:'Know what changed.',sub:'Decide what matters.',intro:'A considered view of Japan and the world. Evidence first, useful signals, and predictions that stay on the record.',brief:'The briefing',signals:'Signals',markets:'Markets',editLayout:'Edit layout',addSymbol:'Add symbol…',done:'Done',hint:'Search a symbol to add · drag to reorder · hide or remove in edit mode',all:'All',ai:'AI',"japan-residence":'Residency & rules',"japan-life":'Japan · everyday life',geopolitics:'Geopolitics',crypto:'Crypto',stocks:'Stocks',ledger:'Prediction ledger',sources:'Source health',stale:'Data is stale. Check the original before acting.',empty:'The first verified briefing is being prepared.',search:'Search signals…',audience:'Who it affects',action:'Next step',unknowns:'What remains unknown',evidence:'Read the evidence',original:'Original source',disclaimer:'Experimental forecast, not investment advice. The first fresh observation after the deadline determines the result.',due:'Resolves after',prob:'Probability',open:'Open',hit:'Hit',miss:'Miss',unresolved:'Unresolved',noForecast:'No forecast has been published yet.',noresults:'No matching signals.',method:'Method',methodText:'Public sources are checked, changes are deduplicated, and native editions are written from the same evidence. Selection is editorial and bounded, not an exhaustive feed. Unknown applicability stays unknown. No personal profiles are published.',healthy:'healthy sources',before:'Published forecasts are immutable. Misses remain visible.',read:'Read the source',generated:'AI-assisted analysis · primary-source verification required',overview:'Overview'},
  ja:{tag:'独立インテリジェンス',hero:'変化を捉える。',sub:'判断につなげる。',intro:'日本と世界を根拠から読み解く。役立つ変化と、結果を検証できる予測を。',brief:'今回の見立て',signals:'注目の変化',markets:'マーケット',editLayout:'表示を編集',addSymbol:'銘柄を追加…',done:'完了',hint:'銘柄を検索して追加 · ドラッグで並べ替え · 編集モードで非表示/削除',all:'すべて',ai:'AI',"japan-residence":'在留・制度',"japan-life":'日本での暮らし',geopolitics:'地政学',crypto:'暗号資産',stocks:'株式',ledger:'予測の記録',sources:'情報源の状態',stale:'情報が古くなっています。行動の前に原文を確認してください。',empty:'検証済みの初回ブリーフィングを準備中です。',search:'変化を検索…',audience:'関係する人',action:'次の一歩',unknowns:'未確認の点',evidence:'根拠を確認',original:'一次情報',disclaimer:'実験的な予測であり、投資助言ではありません。期限後の最初の新しい観測で判定します。',due:'判定開始',prob:'確率',open:'未決着',hit:'的中',miss:'不的中',unresolved:'判定保留',noForecast:'公開された予測はまだありません。',noresults:'該当する情報はありません。',method:'編集方針',methodText:'公開情報を確認し、変化を重複なく追跡。同じ根拠から各言語で独立した文章を作成します。全件収集ではなく、範囲を定めた編集です。適用条件が不明なら不明と示し、個人の情報は公開しません。',healthy:'正常な情報源',before:'公開した予測は書き換えません。外れた記録も残します。',read:'原文を読む',generated:'AI 支援による分析 · 一次情報で要確認',overview:'概要'},
  zh:{tag:'独立情报',hero:'看见变化。',sub:'形成判断。',intro:'从依据出发观察日本与世界。先看证据，只看有用的变化，每次预判都留下可核查的记录。',brief:'本期判断',signals:'信号',markets:'行情',editLayout:'编辑布局',addSymbol:'添加代码…',done:'完成',hint:'搜索代码添加 · 拖拽排序 · 编辑模式可隐藏或删除',all:'全部',ai:'AI 圈',"japan-residence":'日本在留',"japan-life":'日本生活',geopolitics:'地缘政治',crypto:'加密',stocks:'股票',ledger:'预测记账本',sources:'信源状态',stale:'数据已陈旧，采取行动前请核对原文。',empty:'正在准备首份经过核验的简报。',search:'搜索信号…',audience:'影响谁',action:'最小行动',unknowns:'尚未确认',evidence:'查看依据',original:'原始来源',disclaimer:'实验性预测，不构成投资建议。以到期后首次新报价判定结果。',due:'开始结算',prob:'概率',open:'待结算',hit:'命中',miss:'未命中',unresolved:'待核查',noForecast:'尚无已发布预测。',noresults:'没有匹配的信号。',method:'编辑方法',methodText:'核查公开信源、识别变化并去重，从同一组依据分别写成三语内容。这里是有范围的编辑筛选，不是全量信息流。资格不明就保留未知，不公开任何个人匹配资料。',healthy:'健康信源',before:'预测发布后保留原文，未命中的记录也不会删除。',read:'阅读原文',generated:'AI 辅助分析 · 行动前请核对一手来源',overview:'概览'}
};
function formatDate(s:string,l:Locale){return new Intl.DateTimeFormat(l==='zh'?'zh-CN':l==='ja'?'ja-JP':'en-GB',{timeZone:'Asia/Tokyo',month:'short',day:'numeric',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(s))+' JST';}
function EventCard({e,index,l,w}:{e:Snapshot['events'][number];index:number;l:Locale;w:Record<string,string>}){
  return <article data-event data-category={e.category} class="card card-hover p-5 animate-in">
    <div class="flex items-center justify-between mb-3"><span class="badge badge-secondary">{w[e.category]||e.category}</span><span class="text-[11px] text-muted-foreground truncate ml-3">{e.source}</span></div>
    <a href={e.url} target="_blank" rel="noopener noreferrer"><h3 class="font-semibold leading-snug">{e.title[l]} <span class="text-muted-foreground">↗</span></h3></a>
    <p class="text-sm text-muted-foreground mt-2 leading-relaxed">{e.summary[l]}</p>
    <div class="mt-4 rounded-md border-l-2 border-primary bg-muted/50 p-3"><p class="text-[10px] font-semibold uppercase tracking-wide text-muted-foreground mb-1">{w.action}</p><p class="text-sm leading-relaxed">{e.action[l]}</p></div>
    <details class="mt-4 text-xs text-muted-foreground"><summary class="cursor-pointer select-none">{w.evidence}</summary><dl class="mt-3 space-y-2 leading-relaxed"><div><dt class="font-semibold text-foreground/80">{w.audience}</dt><dd>{e.audience[l]}</dd></div><div><dt class="font-semibold text-foreground/80">{w.unknowns}</dt><dd>{e.unknowns[l]}</dd></div><div><dt class="font-semibold text-foreground/80">{w.original}</dt><dd>{e.evidence}</dd></div></dl><a href={e.url} target="_blank" rel="noopener noreferrer" class="inline-block mt-3 underline">{w.read}</a></details>
  </article>;
}
async function ledger(db:D1Database){return (await db.prepare('SELECT * FROM forecasts ORDER BY created_at DESC LIMIT 20').all()).results;}
async function settle(env:Bindings,s:Snapshot){
  const rows=(await env.DB.prepare("SELECT * FROM forecasts WHERE status='open' AND due_at<=? LIMIT 100").bind(new Date().toISOString()).all()).results;
  for(const r of rows){const result=resolveForecast({symbol:r.symbol,baseline:r.baseline,direction:r.direction,dueAt:r.due_at},s.markets);
    if(result)await env.DB.prepare("UPDATE forecasts SET status=?,observed=?,observation_at=?,resolved_at=? WHERE id=? AND status='open'").bind(result.status,result.observed,result.observationAt,result.resolvedAt,r.id).run();}
}
// GitHub's scheduled workflows are unreliable on new repos, so the Worker's own
// cron (reliable) dispatches the sweep when the snapshot goes stale.
async function dispatchSweep(env:Bindings){if(!env.GH_DISPATCH_TOKEN)return {ok:false,reason:'GH_DISPATCH_TOKEN unset'};try{const r=await fetch('https://api.github.com/repos/Antisubmissivist/antist-radar/actions/workflows/sweep.yml/dispatches',{method:'POST',headers:{Authorization:`Bearer ${env.GH_DISPATCH_TOKEN}`,Accept:'application/vnd.github+json','User-Agent':'antist-radar','Content-Type':'application/json'},body:JSON.stringify({ref:'main'})});return {ok:r.ok,status:r.status};}catch(e){return {ok:false,reason:String(e)};}}
function briefingText(s:Snapshot,l:Locale){const ev=s.events.slice(0,8);const lines=[`Antist Radar · ${formatDate(s.generatedAt,l)}`,'',s.digest[l],''];for(const e of ev){lines.push(`• ${e.title[l]}`,`  ${e.action[l]}`,`  ${e.url}`);}for(const f of (s.forecasts||[])){lines.push('',`Forecast: ${f.symbol} ${f.direction} ${Math.round(Number(f.probability)*100)}% (due ${f.dueAt.slice(0,10)})`);}return lines.join('\n');}
app.use('*',async(c,next)=>{await next();c.header('X-Content-Type-Options','nosniff');c.header('Referrer-Policy','strict-origin-when-cross-origin');c.header('X-Frame-Options','DENY');});
app.get('/',c=>c.redirect('/en',302));
app.get('/robots.txt',c=>c.text(`User-agent: *\nAllow: /\nDisallow: /api/ingest\nSitemap: ${ORIGIN}/sitemap.xml`));
app.get('/sitemap.xml',c=>c.body(`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${languages.map(l=>`<url><loc>${ORIGIN}/${l}</loc></url>`).join('')}</urlset>`,200,{'Content-Type':'application/xml'}));
app.get('/api/public',async c=>{const s=await c.env.MONITOR.get(KEY);c.header('Cache-Control','no-store');return s?c.body(s,200,{'Content-Type':'application/json'}):c.json({status:'pending'},503);});
app.get('/api/ledger',async c=>c.json({forecasts:await ledger(c.env.DB)}));
app.get('/api/markets',async c=>{const q=c.req.query('symbols');const symbols=q?q.split(',').map(x=>x.trim()).filter(Boolean):undefined;const m=await getMarkets(c.env,symbols);c.header('Cache-Control','no-store');return c.json(m);});
app.get('/api/symbols',async c=>{const q=(c.req.query('q')||'').trim();if(!q)return c.json({results:[]});c.header('Cache-Control','public, max-age=300');return c.json({results:await searchSymbols(q.slice(0,40))});});
app.get('/api/briefing',async c=>{const raw=c.req.query('lang')||'zh';const L=(languages as readonly string[]).includes(raw)?raw as Locale:'zh';const s=await c.env.MONITOR.get<Snapshot>(KEY,'json');if(!s)return c.json({status:'pending'},503);const events=s.events.slice(0,8).map(e=>({category:e.category,title:e.title[L],action:e.action[L],url:e.url}));const forecasts=(s.forecasts||[]).map(f=>({symbol:f.symbol,direction:f.direction,probability:f.probability,dueAt:f.dueAt,claim:f.claim[L]}));c.header('Cache-Control','no-store');if(c.req.query('format')==='text')return c.text(briefingText(s,L));return c.json({lang:L,updatedAt:s.generatedAt,digest:s.digest[L],events,forecasts,text:briefingText(s,L)});});
app.post('/api/dispatch',async c=>{const expected=`Bearer ${c.env.RADAR_INGEST_TOKEN||''}`;if(!c.env.RADAR_INGEST_TOKEN||c.req.header('Authorization')!==expected)return c.json({ok:false},401);return c.json(await dispatchSweep(c.env));});
app.get('/llms.txt',c=>c.text(['# Antist Radar API','','Independent Japan+world intelligence radar. Public, read-only JSON.','','GET /api/public            Full snapshot (schema 2): digest(ja/en/zh), events, markets, sources, forecasts','GET /api/briefing?lang=zh  Concise briefing for agents/Telegram; add &format=text for plain text','GET /api/ledger            Published forecasts and their settled results','GET /api/markets?symbols=  Live quotes for any comma-separated Yahoo symbols','GET /api/symbols?q=        Symbol search (returns symbol, name, exchange)','','Write endpoints require Authorization: Bearer <token>:','POST /api/ingest  POST /api/digest  POST /api/watchlist  POST /api/dispatch','','Forecasts are experimental and not investment advice.'].join('\n'),200,{'Content-Type':'text/plain; charset=utf-8'}));
app.post('/api/watchlist',async c=>{const expected=`Bearer ${c.env.RADAR_INGEST_TOKEN||''}`;if(!c.env.RADAR_INGEST_TOKEN||c.req.header('Authorization')!==expected)return c.json({ok:false},401);const body=await c.req.json().catch(()=>null) as {symbols?:unknown}|null;if(!Array.isArray(body?.symbols))return c.json({ok:false,reason:'symbols[] required'},400);const list=(body!.symbols as unknown[]).filter((s):s is {symbol:string;name?:string}=>!!s&&typeof (s as {symbol?:unknown}).symbol==='string').slice(0,30).map(s=>({symbol:String(s.symbol).slice(0,24),name:String(s.name||s.symbol).slice(0,40)}));await setWatchlist(c.env,list);return c.json({ok:true,count:list.length});});
app.post('/api/digest',async c=>{const expected=c.env.RADAR_INGEST_TOKEN;if(!expected||c.req.header('Authorization')!==`Bearer ${expected}`)return c.json({ok:false},401);const s=await c.env.MONITOR.get<Snapshot>(KEY,'json');if(!s)return c.json({status:'pending'},503);return c.json(await sendDigest(c.env,s));});
app.post('/api/ingest',async c=>{
  const actual=c.req.header('Authorization')||'';const expected=`Bearer ${c.env.RADAR_INGEST_TOKEN||''}`;
  const hash=async(v:string)=>new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(v)));
  const [a,b]=await Promise.all([hash(actual),hash(expected)]);let diff=0;for(let i=0;i<a.length;i++)diff|=a[i]^b[i];
  if(!c.env.RADAR_INGEST_TOKEN||diff!==0)return c.json({ok:false},401);
  if(Number(c.req.header('Content-Length')||0)>700000)return c.json({ok:false},413);
  let s:Snapshot;try {const reader=c.req.raw.body?.getReader();if(!reader)return c.json({ok:false},400);const decoder=new TextDecoder();let raw='',size=0;for(;;){const {done,value}=await reader.read();if(done)break;size+=value.byteLength;if(size>700000){await reader.cancel();return c.json({ok:false},413);}raw+=decoder.decode(value,{stream:true});}raw+=decoder.decode();s=publicSnapshot(JSON.parse(raw));}catch{return c.json({ok:false,reason:'invalid public payload'},400);}
  if(Math.abs(Date.now()-Date.parse(s.generatedAt))>7200000)return c.json({ok:false,reason:'stale publication'},409);
  const current=await c.env.MONITOR.get<Snapshot>(KEY,'json');
  if(current&&Date.parse(current.generatedAt)>Date.parse(s.generatedAt))return c.json({ok:false,reason:'out of order'},409);
  const key=`snapshots/${s.generatedAt.slice(0,10)}/${s.id}.json`;
  for(const f of (s.forecasts||[])){await c.env.DB.prepare('INSERT OR IGNORE INTO forecasts (id,created_at,due_at,symbol,baseline,direction,probability,claim_json,rationale_json,evidence_json) VALUES (?,?,?,?,?,?,?,?,?,?)').bind(f.id,f.createdAt,f.dueAt,f.symbol,f.baseline,f.direction,f.probability,JSON.stringify(f.claim),JSON.stringify(f.rationale),JSON.stringify(f.evidence)).run();}
  for(const f of (s.forecasts||[])){const r=await c.env.DB.prepare('SELECT * FROM forecasts WHERE id=?').bind(f.id).first();if(r){f.createdAt=String(r.created_at);f.dueAt=String(r.due_at);f.symbol=String(r.symbol);f.baseline=Number(r.baseline);f.direction=r.direction==='above'?'above':'below';f.probability=Number(r.probability);f.claim=JSON.parse(String(r.claim_json));f.rationale=JSON.parse(String(r.rationale_json));f.evidence=JSON.parse(String(r.evidence_json));}}
  await c.env.ARCHIVE.put(key,JSON.stringify(s),{httpMetadata:{contentType:'application/json'}});
  await settle(c.env,s);
  await c.env.DB.prepare('INSERT OR IGNORE INTO sweeps (id,fetched_at,published_at,source_count,healthy_count,event_count,archive_key) VALUES (?,?,?,?,?,?,?)').bind(s.id,s.generatedAt,new Date().toISOString(),s.sources.length,s.sources.filter(x=>['ok','quiet'].includes(x.status)).length,s.events.length,key).run();
  await c.env.MONITOR.put('radar:ledger',JSON.stringify(await ledger(c.env.DB)));
  await c.env.MONITOR.put(KEY,JSON.stringify(s));return c.json({ok:true,id:s.id,archived:true});
});
app.get('/:locale',async c=>{
  const l=c.req.param('locale') as Locale;if(!languages.includes(l))return c.notFound();
  const w=words[l];const [s,cachedLedger]=await Promise.all([c.env.MONITOR.get<Snapshot>(KEY,'json'),c.env.MONITOR.get<Record<string,unknown>[]>('radar:ledger','json')]);const rows=cachedLedger||[];
  const stale=!s||Date.now()-Date.parse(s.generatedAt)>150*60000;
  const healthy=s?.sources.filter(x=>['ok','quiet'].includes(x.status)).length||0;
  const strip=(s?.markets.filter(q=>STRIP.includes(q.symbol))||[]);
  c.header('Cache-Control','no-store');c.header('Content-Language',l);
  return c.html(<html lang={l}><head><meta charset="utf-8"/><meta name="viewport" content="width=device-width,initial-scale=1"/><title>{titles[l]}</title><meta name="description" content={descriptions[l]}/><link rel="canonical" href={`${ORIGIN}/${l}`}/>{languages.map(lang=><link rel="alternate" hreflang={lang} href={`${ORIGIN}/${lang}`}/>)}<link rel="alternate" hreflang="x-default" href={`${ORIGIN}/en`}/><meta property="og:title" content={titles[l]}/><meta property="og:description" content={descriptions[l]}/><meta property="og:url" content={`${ORIGIN}/${l}`}/><meta property="og:type" content="website"/><meta property="og:image" content={`${ORIGIN}/og.png`}/><meta property="og:image:width" content="1200"/><meta property="og:image:height" content="630"/><meta property="og:image:alt" content="Antist Radar"/><meta name="twitter:card" content="summary_large_image"/><meta name="twitter:title" content={titles[l]}/><meta name="twitter:description" content={descriptions[l]}/><meta name="twitter:image" content={`${ORIGIN}/og.png`}/><meta name="theme-color" content="#0a0a0b"/><link rel="icon" type="image/png" sizes="512x512" href="/favicon-512.png"/><link rel="icon" type="image/png" sizes="32x32" href="/favicon-32.png"/><link rel="apple-touch-icon" href="/apple-touch-icon.png"/><link rel="stylesheet" href="/style.css"/>{html`<script>try{if((localStorage.getItem('radar-theme')||'dark')==='dark')document.documentElement.classList.add('dark')}catch{}</script>`}<script src="/app.js" defer/></head>
  <body><header class="sticky top-0 z-40 w-full border-b bg-background/80 backdrop-blur supports-[backdrop-filter]:bg-background/60"><div class="mx-auto max-w-6xl h-16 px-4 md:px-6 flex items-center justify-between gap-4"><a href={`/${l}`} class="flex items-center gap-2 font-semibold tracking-tight"><span class="grid h-7 w-7 place-items-center rounded-md bg-primary text-primary-foreground text-xs font-bold">A</span><span>ANTIST<span class="text-muted-foreground font-normal"> / RADAR</span></span></a><nav class="hidden md:flex items-center gap-1"><a href="#signals" class="tab">{w.overview}</a><a href="#markets" class="tab">{w.markets}</a><a href="#ledger" class="tab">{w.ledger}</a><a href="#sources" class="tab">{w.sources}</a></nav><div class="flex items-center gap-2"><div class="flex items-center rounded-lg bg-muted p-1">{languages.map(lang=><a href={`/${lang}`} class={`tab px-2.5 py-1 text-xs ${lang===l?'tab-active':''}`}>{lang.toUpperCase()}</a>)}</div><button data-theme class="btn btn-ghost btn-icon" aria-label="Toggle theme">◐</button></div></div></header>
  <main class="mx-auto max-w-6xl px-4 md:px-6 pb-16"><section class="py-12 md:py-16 grid lg:grid-cols-[1.4fr_1fr] gap-8 items-start"><div><span class="badge badge-secondary mb-5 gap-1.5">{(stale?<span class="inline-block h-2 w-2 rounded-full bg-down"/>:<span class="live-dot inline-block h-2 w-2 rounded-full bg-up"/>)} {w.tag}</span><h1 class="text-4xl md:text-5xl lg:text-6xl font-bold tracking-tight leading-[1.06]">{w.hero}<br/><span class="text-muted-foreground">{w.sub}</span></h1><p class="mt-5 max-w-xl text-muted-foreground leading-relaxed">{w.intro}</p></div><div class="card p-6"><div class="flex items-center justify-between text-xs text-muted-foreground mb-3"><span class="uppercase tracking-wide">{w.brief}</span><span class="tabular-nums">{s?formatDate(s.generatedAt,l):'—'}</span></div><p class="text-base leading-relaxed">{s?.digest[l]||w.empty}</p><p class="text-[11px] text-muted-foreground mt-4">{w.generated}</p></div></section>
  {stale&&<div role="status" class="mb-8 rounded-lg border border-destructive/30 bg-destructive/10 px-4 py-3 text-sm text-destructive">{w.stale}</div>}
  <section id="markets" class="mb-12"><div class="card p-4 md:p-5"><div class="flex flex-wrap items-center justify-between gap-3 mb-4"><div class="flex items-center gap-2"><h2 class="text-sm font-semibold tracking-tight">{w.markets}</h2><span class="badge badge-outline gap-1.5 text-[10px]"><span class="live-dot inline-block h-1.5 w-1.5 rounded-full bg-up"></span>LIVE</span><span data-markets-status class="text-[11px] text-muted-foreground"></span></div><div class="flex items-center gap-2"><div class="relative"><input data-markets-search class="input h-8 w-44 text-xs" placeholder={w.addSymbol} autocomplete="off"/><div data-markets-suggest class="absolute right-0 top-9 z-50 hidden w-72 overflow-hidden rounded-md border bg-popover text-popover-foreground shadow-md"></div></div><button data-markets-done class="btn btn-primary btn-sm hidden">{w.done}</button><button data-markets-edit class="btn btn-outline btn-sm">{w.editLayout}</button></div></div><div data-markets class="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 gap-2">{strip.map(q=><a href={q.source} target="_blank" rel="noopener noreferrer" class="market-tile"><div class="text-[11px] font-medium text-muted-foreground truncate">{q.name}</div><div class="flex items-baseline justify-between gap-2"><span class="text-lg font-semibold tabular-nums">{q.price.toLocaleString(l,{maximumFractionDigits:2})}</span><span class={`text-xs font-medium tabular-nums ${q.changePct>=0?'text-up':'text-down'}`}>{q.changePct>=0?'+':''}{q.changePct}%</span></div></a>)}</div><p class="text-[11px] text-muted-foreground mt-3 hidden md:block">{w.hint}</p></div></section>
  <section id="signals" class="mb-5"><div class="flex flex-wrap items-center justify-between gap-3 mb-4"><h2 class="text-xl font-semibold tracking-tight">{w.signals} <span class="text-sm text-muted-foreground tabular-nums">{String(s?.events.length||0).padStart(2,'0')}</span></h2><input data-search type="search" class="input h-9 w-full sm:w-64" placeholder={w.search}/></div><div class="inline-flex flex-wrap items-center gap-0.5 rounded-lg bg-muted p-1">{(['all',...BOARDS] as string[]).map((cat,i)=><button data-filter={cat} aria-pressed={i===0?'true':'false'} class={`tab ${i===0?'tab-active':''}`}>{(w as Record<string,string>)[cat]}</button>)}</div></section>
  {BOARDS.map(b=>{const list=(s?.events||[]).filter(e=>e.category===b);return <section id={`board-${b}`} data-board={b} class="mb-10"><div class="flex items-baseline justify-between mb-4"><h3 class="text-lg font-semibold tracking-tight">{w[b]} <span class="text-xs text-muted-foreground tabular-nums">{String(list.length).padStart(2,'0')}</span></h3></div>{list.length?<div class="grid md:grid-cols-2 gap-4">{list.map((e,i)=><EventCard e={e} index={i} l={l} w={w}/>)}</div>:<p class="text-sm text-muted-foreground">{w.noresults}</p>}</section>;})}
  <p data-no-results hidden class="py-12 text-center text-muted-foreground">{w.noresults}</p>
  <section id="ledger" class="py-12 border-t"><div class="mb-6"><p class="text-[10px] uppercase tracking-widest text-muted-foreground mb-2">On the record</p><h2 class="text-xl font-semibold tracking-tight">{w.ledger}</h2><p class="text-sm text-muted-foreground mt-1">{w.before}</p></div><div class="grid md:grid-cols-2 gap-4">{rows.length?rows.map(r=>{const claim=JSON.parse(String(r.claim_json));const rationale=JSON.parse(String(r.rationale_json));return <div class="card p-5"><div class="flex items-center justify-between mb-4"><span class="badge badge-secondary">{w[String(r.status) as keyof typeof w]||r.status}</span><span class="text-xs text-muted-foreground tabular-nums">{String(r.created_at).slice(0,10)}</span></div><h3 class="font-semibold leading-relaxed">{claim[l]}</h3><p class="text-sm text-muted-foreground mt-2 leading-relaxed">{rationale[l]}</p><div class="grid grid-cols-2 gap-4 border-t mt-5 pt-4"><div><div class="text-[10px] text-muted-foreground">{w.prob}</div><div class="text-2xl font-semibold tabular-nums mt-0.5">{Math.round(Number(r.probability)*100)}%</div></div><div><div class="text-[10px] text-muted-foreground">{w.due}</div><div class="text-xs tabular-nums mt-1.5">{formatDate(String(r.due_at),l)}</div></div></div>{r.observed!=null&&<p class="text-xs tabular-nums mt-3">{r.symbol}: {r.observed} · {r.observation_at}</p>}<p class="text-[10px] text-muted-foreground mt-4 leading-relaxed">{w.disclaimer}</p></div>}):<p class="text-sm text-muted-foreground">{w.noForecast}</p>}</div></section>
  <section id="sources" class="py-12 border-t grid md:grid-cols-[1fr_2fr] gap-8"><div><h2 class="text-xl font-semibold tracking-tight">{w.sources}</h2><p class="text-4xl font-semibold tabular-nums mt-3">{healthy}<span class="text-xl text-muted-foreground"> / {s?.sources.length||0}</span></p><p class="text-xs text-muted-foreground mt-1">{w.healthy}</p></div><div class="grid sm:grid-cols-3 gap-x-4">{s?.sources.map(source=><a href={source.url} target="_blank" rel="noopener noreferrer" class="flex justify-between gap-3 border-b py-2.5 text-xs"><span class="truncate">{source.name}</span><span class={['ok','quiet'].includes(source.status)?'text-up':'text-muted-foreground'}>{source.status}</span></a>)}</div></section>
  <footer class="border-t py-10 grid md:grid-cols-2 gap-8"><div><p class="text-sm font-semibold tracking-tight">ANTIST / RADAR.</p><p class="text-xs text-muted-foreground mt-3">Japan & the world. Independently observed.</p><a class="text-xs text-muted-foreground underline mt-2 inline-block" href="https://github.com/Antisubmissivist/antist-radar">Source code · AGPL-3.0</a></div><div><h2 class="text-xs font-semibold mb-2">{w.method}</h2><p class="text-xs text-muted-foreground leading-relaxed">{w.methodText}</p></div></footer></main></body></html>);
});
app.onError((_err,c)=>c.json({error:'Temporarily unavailable'},503));
export default {fetch:app.fetch,async scheduled(event:ScheduledController,env:Bindings){const s=await env.MONITOR.get<Snapshot>(KEY,'json');if(!s||Date.now()-Date.parse(s.generatedAt)>50*60000){console.log(JSON.stringify({event:'sweep-dispatch',...(await dispatchSweep(env))}));}if(s){await settle(env,s);await env.MONITOR.put('radar:ledger',JSON.stringify(await ledger(env.DB)));if(new Date(event.scheduledTime+9*3600000).getUTCHours()>=8){const result=await sendDigest(env,s,event.scheduledTime);console.log(JSON.stringify({event:'daily-delivery',...result}));}}}};
